#!/usr/bin/env python3

import argparse
import json
import re
import sys
from pathlib import Path

import validate_hsaco_routes as route_validator


ATTRIBUTE_INDICES = {
    "GGML_OP_ARGSORT": {
        "order": 0,
    },
    "GGML_OP_CLAMP": {
        "minimum": 0,
        "maximum": 1,
    },
    "GGML_OP_SCALE": {
        "scale": 0,
        "bias": 1,
    },
    "GGML_OP_SOFT_MAX": {
        "scale": 0,
        "max_bias": 1,
    },
}

CPP_SCALAR_TYPES = {
    "f32": "float",
    "f64": "double",
    "i32": "int32_t",
    "i64": "int64_t",
}

CPP_DTYPE_NAMES = {
    "F32": "GGML_TYPE_F32",
    "I32": "GGML_TYPE_I32",
}

UNSUPPORTED_REASON_BY_PREDICATE = {
    "contiguous": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_LAYOUT",
    "same_shape": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    "rank": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    "field": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    "src_absent": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    "src_present": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
}

ATTRIBUTE_GETTERS = {
    "f32": "ggml_get_op_params_f32",
    "f64": "ggml_get_op_params_f32",
    "i32": "ggml_get_op_params_i32",
    "i64": "ggml_get_op_params_i32",
}

ROUTE_HEADER_TEMPLATE = """// Generated by generate_hsaco_route_impl.py.
// Include this file from ggml-hrx-hsaco-catalog-runtime.cpp after the catalog runtime helper types are declared.
// Expected host API: ggml_backend_hrx_hsaco_execution_plan, response helpers, route lookup, bind helper, and dispatch helpers.

static constexpr const char * {route_id_constant} = {route_id_literal};
"""

ROUTE_FUNCTION_OPEN_TEMPLATE = """static ggml_backend_hrx_hsaco_op_response {function_name}(
        ggml_backend_hrx_hsaco_catalog * catalog,
        const ggml_backend_hrx_hsaco_op_request * request,
        ggml_backend_hrx_hsaco_execution_plan * plan) {{
    if (!catalog || !request || !request->op) {{
        return ggml_backend_hrx_hsaco_failed(nullptr);
    }}
    const ggml_tensor * node = request->op;
    if (node->op != {op}) {{
        return ggml_backend_hrx_hsaco_unsupported(GGML_BACKEND_HRX_HSACO_UNSUPPORTED_NO_ROUTE);
    }}
    const ggml_backend_hrx_hsaco_catalog_entry * entry = ggml_backend_hrx_hsaco_find_entry(catalog, {route_id_constant});
    if (!entry) {{
        return ggml_backend_hrx_hsaco_unsupported(GGML_BACKEND_HRX_HSACO_UNSUPPORTED_TARGET);
    }}"""

PLAN_SETUP_TEMPLATE = """
    if (!plan) {{
        return ggml_backend_hrx_hsaco_supported({route_id_constant});
    }}
    if (!request->stream || !request->bind_tensor) {{
        return ggml_backend_hrx_hsaco_failed({route_id_constant});
    }}
    std::memset(plan, 0, sizeof(*plan));
    plan->entry = entry;"""

BIND_BUFFER_TEMPLATE = """    if (!ggml_backend_hrx_hsaco_bind_tensor(request, {tensor}, &plan->bindings[{position}])) {{
        return ggml_backend_hrx_hsaco_failed({route_id_constant});
    }}"""

PACK_SCALAR_TEMPLATE = """    const {cpp_type} {name} = {value};
    std::memcpy(plan->constants + {offset}, &{name}, sizeof({name}));"""


def cpp_string(value):
    return json.dumps(value)


def c_identifier(value):
    return re.sub(r"[^A-Za-z0-9_]", "_", value)


def role_expr(role):
    if role == "dst":
        return "node"
    if role.startswith("src") and role[3:].isdigit():
        return f"node->src[{int(role[3:])}]"
    raise ValueError(f"unsupported tensor role {role}")


def role_var(role):
    return c_identifier(role)


def derived_var(name):
    return f"derived_{c_identifier(name)}"


def attribute_var(name):
    return f"attribute_{c_identifier(name)}"


def route_id_constant(route_id):
    return f"GGML_HRX_HSACO_ROUTE_ID_{c_identifier(route_id).upper()}"


def scalar_literal(value, scalar_type):
    def float_text(number, precision):
        text = f"{float(number):.{precision}g}"
        if "e" not in text and "E" not in text and "." not in text:
            text += ".0"
        return text

    if scalar_type == "f32":
        return f"{float_text(value, 9)}f"
    if scalar_type == "f64":
        return float_text(value, 17)
    if scalar_type in {"i32", "i64"}:
        return str(int(value))
    raise ValueError(f"unsupported scalar literal type {scalar_type}")


def emit_tensor_type_source(tensor, parts):
    if len(parts) != 3:
        raise ValueError("tensor type source does not accept an index")
    return f"{tensor}->type"


def emit_tensor_rank_source(tensor, parts):
    if len(parts) != 3:
        raise ValueError("tensor rank source does not accept an index")
    return f"ggml_n_dims({tensor})"


def emit_tensor_element_count_source(tensor, parts):
    if len(parts) != 3:
        raise ValueError("tensor element_count source does not accept an index")
    return f"ggml_nelements({tensor})"


def emit_tensor_vector_source(tensor, parts, field):
    if len(parts) == 3:
        field_name = "ne" if field == "dimensions" else "nb"
        return [f"{tensor}->{field_name}[{i}]" for i in range(4)]
    field_name = "ne" if field == "dimensions" else "nb"
    return f"{tensor}->{field_name}[{int(parts[3])}]"


def emit_tensor_dimensions_source(tensor, parts):
    return emit_tensor_vector_source(tensor, parts, "dimensions")


def emit_tensor_strides_source(tensor, parts):
    return emit_tensor_vector_source(tensor, parts, "strides")


TENSOR_FIELD_EMITTERS = {
    "type": emit_tensor_type_source,
    "rank": emit_tensor_rank_source,
    "element_count": emit_tensor_element_count_source,
    "dimensions": emit_tensor_dimensions_source,
    "strides": emit_tensor_strides_source,
}


def emit_tensor_source(parts):
    if len(parts) not in {3, 4}:
        raise ValueError("unsupported tensor source")
    role = parts[1]
    field = parts[2]
    emitter = TENSOR_FIELD_EMITTERS.get(field)
    if emitter is None:
        raise ValueError(f"unsupported tensor source field {field}")
    return emitter(role_var(role), parts)


def emit_attribute_source(parts):
    if len(parts) != 2:
        raise ValueError("unsupported attribute source")
    return attribute_var(parts[1])


def emit_derived_source(parts):
    if len(parts) != 2:
        raise ValueError("unsupported derived source")
    return derived_var(parts[1])


SOURCE_EMITTERS = {
    "tensor": emit_tensor_source,
    "attribute": emit_attribute_source,
    "derived": emit_derived_source,
}


def source_expr(source):
    parts = source.split(".")
    emitter = SOURCE_EMITTERS.get(parts[0])
    if emitter is None:
        raise ValueError(f"unsupported source {source}")
    return emitter(parts)


def source_type(source, context):
    return context.resolve_source(source, source)


def typed_expr(expr, scalar_type):
    return f"static_cast<{CPP_SCALAR_TYPES[scalar_type]}>({expr})"


def route_response(reason):
    return f"return ggml_backend_hrx_hsaco_unsupported({reason});"


def load_route(source_root, route_name):
    source_root = source_root.resolve()
    route_path = Path(route_name)
    if not route_path.is_absolute():
        route_path = source_root / route_path
    route_path = route_path.resolve()

    definitions = route_validator.load_definitions(source_root)
    route_validator.validate_route(route_path, definitions)
    route = route_validator.read_json(route_path)
    definition_path = (route_path.parent / route_validator.require_string(route, "definition", route_path)).resolve()
    definition = definitions[definition_path]
    return route_path, route, definition_path, definition


def validate_attribute_indices(route, route_path):
    match = route_validator.require_dict(route, "match", route_path)
    op = route_validator.require_string(match, "op", f"{route_path}: match")
    attributes = match.get("attributes", {})
    indices = ATTRIBUTE_INDICES.get(op, {})
    for name in attributes:
        if name not in indices:
            raise ValueError(f"{route_path}: no generated C++ attribute index for {op}.{name}")


def scalar_offsets(scalars, route_path):
    offsets = []
    offset = 0
    for scalar in scalars:
        scalar_type = route_validator.require_string(scalar, "type", route_path)
        size, alignment = route_validator.SUPPORTED_SCALAR_TYPES[scalar_type]
        offset = route_validator.align_offset(offset, alignment)
        offsets.append(offset)
        offset += size
    return offsets, offset


def emit_header(lines, route):
    route_id = route_validator.require_string(route, "id", "route")
    lines.append(ROUTE_HEADER_TEMPLATE.format(
        route_id_constant=route_id_constant(route_id),
        route_id_literal=cpp_string(route_id),
    ))


def emit_tensor_setup(lines, route, op_rule):
    tensors = route_validator.require_dict(route_validator.require_dict(route, "match", "route"), "tensors", "route")
    for role in tensors:
        lines.append(f"    const ggml_tensor * {role_var(role)} = {role_expr(role)};")

    required = sorted(op_rule["required_tensors"] & set(tensors))
    if required:
        condition = " || ".join([f"!{role_var(role)}" for role in required])
        lines.extend([
            f"    if ({condition}) {{",
            f"        {route_response('GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE')}",
            "    }",
        ])

    optional_present = []
    for role, tensor in tensors.items():
        if role in op_rule["optional_tensors"] and tensor.get("optional", False):
            optional_present.append(role)
    for role in optional_present:
        lines.append(f"    const bool {role_var(role)}_present = {role_var(role)} != nullptr;")


def emit_dtype_checks(lines, route):
    tensors = route_validator.require_dict(route_validator.require_dict(route, "match", "route"), "tensors", "route")
    checks = []
    for role, tensor in tensors.items():
        dtype = route_validator.require_string(tensor, "type", "route")
        cpp_dtype = CPP_DTYPE_NAMES[dtype]
        if tensor.get("optional", False):
            checks.append(f"({role_var(role)} && {role_var(role)}->type != {cpp_dtype})")
        else:
            checks.append(f"{role_var(role)}->type != {cpp_dtype}")
    if checks:
        lines.extend([
            f"    if ({' || '.join(checks)}) {{",
            f"        {route_response('GGML_BACKEND_HRX_HSACO_UNSUPPORTED_DTYPE')}",
            "    }",
        ])


def emit_attributes(lines, route):
    match = route_validator.require_dict(route, "match", "route")
    op = route_validator.require_string(match, "op", "route")
    attributes = match.get("attributes", {})
    if not attributes:
        return
    indices = ATTRIBUTE_INDICES[op]
    for name, attr in attributes.items():
        scalar_type = route_validator.require_string(attr, "type", "route")
        getter = "ggml_get_op_params_f32" if scalar_type in {"f32", "f64"} else "ggml_get_op_params_i32"
        cast = CPP_SCALAR_TYPES[scalar_type]
        lines.append(f"    const {cast} {attribute_var(name)} = {getter}(node, {indices[name]});")


def emit_product(value, context, scalar_type):
    if isinstance(value, str):
        operands = source_expr(value)
    else:
        operands = [source_expr(item) for item in value]
    expr = " * ".join([typed_expr(operand, scalar_type) for operand in operands])
    return expr if expr else scalar_literal(1, scalar_type)


def emit_ceil_div(value, context, scalar_type):
    lhs = emit_integer_operand(value[0], context)
    rhs = emit_integer_operand(value[1], context)
    return typed_expr(f"({lhs} + {rhs} - 1) / {rhs}", scalar_type)


def emit_next_power_of_2(value, context, scalar_type):
    expr = source_expr(value)
    return typed_expr(f"ggml_backend_hrx_hsaco_next_power_of_2({expr})", scalar_type)


def emit_integer_operand(value, context):
    if route_validator.is_source_string(value):
        return source_expr(value)
    return str(int(value))


def emit_derived_field(item, context, scalar_type):
    del context
    expr = source_expr(route_validator.require_string(item, "field", "route"))
    return typed_expr(expr, scalar_type)


def emit_derived_value(item, context, scalar_type):
    del context
    return scalar_literal(item["value"], scalar_type)


def emit_derived_product(item, context, scalar_type):
    return emit_product(item["product"], context, scalar_type)


def emit_derived_ceil_div(item, context, scalar_type):
    return emit_ceil_div(item["ceil_div"], context, scalar_type)


def emit_derived_next_power_of_2(item, context, scalar_type):
    return emit_next_power_of_2(route_validator.require_string(item, "next_power_of_2", "route"), context, scalar_type)


DERIVED_EMITTERS = {
    "field": emit_derived_field,
    "value": emit_derived_value,
    "product": emit_derived_product,
    "ceil_div": emit_derived_ceil_div,
    "next_power_of_2": emit_derived_next_power_of_2,
}


def emit_derived(lines, route, context):
    derived = route_validator.require_dict(route, "derived", "route")
    for name, item in derived.items():
        scalar_type = route_validator.require_string(item, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        operation = next((key for key in DERIVED_EMITTERS if key in item), None)
        if operation is None:
            raise ValueError(f"unsupported derived operation for {name}")
        expr = DERIVED_EMITTERS[operation](item, context, scalar_type)
        lines.append(f"    const {cpp_type} {derived_var(name)} = {expr};")


def comparator_value_expr(value, field_type, context):
    if route_validator.is_source_string(value):
        return source_expr(value)
    if field_type == "dtype":
        return CPP_DTYPE_NAMES[value]
    if field_type in CPP_SCALAR_TYPES:
        return scalar_literal(value, field_type)
    raise ValueError(f"unsupported comparator value type {field_type}")


def emit_equals_comparator(lhs, value, field_type, context):
    return f"{lhs} == {comparator_value_expr(value, field_type, context)}"


def emit_in_comparator(lhs, value, field_type, context):
    return " || ".join([f"{lhs} == {comparator_value_expr(item, field_type, context)}" for item in value])


def emit_min_comparator(lhs, value, field_type, context):
    return f"{lhs} >= {comparator_value_expr(value, field_type, context)}"


def emit_max_comparator(lhs, value, field_type, context):
    return f"{lhs} <= {comparator_value_expr(value, field_type, context)}"


def emit_multiple_of_comparator(lhs, value, field_type, context):
    del field_type
    del context
    return f"{lhs} % {int(value)} == 0"


COMPARATOR_EMITTERS = {
    "equals": emit_equals_comparator,
    "in": emit_in_comparator,
    "min": emit_min_comparator,
    "max": emit_max_comparator,
    "multiple_of": emit_multiple_of_comparator,
}


def comparator_expr(lhs, comparator, value, field_type, context):
    emitter = COMPARATOR_EMITTERS.get(comparator)
    if emitter is None:
        raise ValueError(f"unsupported comparator {comparator}")
    return emitter(lhs, value, field_type, context)


def emit_contiguous_predicate(predicate, context):
    del context
    return f"ggml_is_contiguous({role_var(predicate['contiguous'])})"


def emit_same_shape_predicate(predicate, context):
    del context
    lhs, rhs = predicate["same_shape"]
    return f"ggml_are_same_shape({role_var(lhs)}, {role_var(rhs)})"


def emit_rank_predicate(predicate, context):
    del context
    return f"ggml_n_dims({role_var(predicate['rank'])}) == {int(predicate['equals'])}"


def emit_field_predicate(predicate, context):
    field = route_validator.require_string(predicate, "field", "route")
    field_type = source_type(field, context)
    lhs = source_expr(field)
    comparator = next(key for key in COMPARATOR_EMITTERS if key in predicate)
    return comparator_expr(lhs, comparator, predicate[comparator], field_type, context)


def emit_src_absent_predicate(predicate, context):
    del context
    return f"{role_expr(predicate['src_absent'])} == nullptr"


def emit_src_present_predicate(predicate, context):
    del context
    return f"{role_expr(predicate['src_present'])} != nullptr"


PREDICATE_EMITTERS = {
    "contiguous": emit_contiguous_predicate,
    "same_shape": emit_same_shape_predicate,
    "rank": emit_rank_predicate,
    "field": emit_field_predicate,
    "src_absent": emit_src_absent_predicate,
    "src_present": emit_src_present_predicate,
}


def emit_predicates(lines, route, context):
    match = route_validator.require_dict(route, "match", "route")
    for predicate in match.get("predicates", []):
        form = next(key for key in PREDICATE_EMITTERS if key in predicate)
        reason = UNSUPPORTED_REASON_BY_PREDICATE[form]
        condition = PREDICATE_EMITTERS[form](predicate, context)
        lines.extend([
            f"    if (!({condition})) {{",
            f"        {route_response(reason)}",
            "    }",
        ])


def emit_flat_1d_dispatch(dispatch, context, route_constant):
    del context
    work_items = source_expr(route_validator.require_string(dispatch, "work_items", "route"))
    return [
        f"    if (!ggml_backend_hrx_hsaco_make_1d_dispatch_config(entry, {work_items}, &plan->dispatch)) {{",
        f"        return ggml_backend_hrx_hsaco_failed({route_constant});",
        "    }",
    ]


def emit_rows_1d_dispatch(dispatch, context, route_constant):
    del context
    rows = source_expr(route_validator.require_string(dispatch, "rows", "route"))
    return [
        f"    if (!ggml_backend_hrx_hsaco_make_row_dispatch_config(entry, {rows}, &plan->dispatch)) {{",
        f"        return ggml_backend_hrx_hsaco_failed({route_constant});",
        "    }",
    ]


def emit_exact_3d_dispatch(dispatch, context, route_constant):
    del route_constant
    workgroup_count = route_validator.require_dict(dispatch, "workgroup_count", "route")
    x = emit_integer_operand(workgroup_count["x"], context)
    y = emit_integer_operand(workgroup_count["y"], context)
    z = emit_integer_operand(workgroup_count["z"], context)
    workgroup_size = dispatch["workgroup_size"]
    return [
        "    plan->dispatch = {",
        f"        /* .workgroup_count = */ {{static_cast<uint32_t>({x}), static_cast<uint32_t>({y}), static_cast<uint32_t>({z})}},",
        f"        /* .workgroup_size  = */ {{{workgroup_size[0]}, {workgroup_size[1]}, {workgroup_size[2]}}},",
        "        /* .subgroup_size   = */ 0,",
        "    };",
    ]


DISPATCH_EMITTERS = {
    "flat_1d": emit_flat_1d_dispatch,
    "rows_1d": emit_rows_1d_dispatch,
    "exact_3d": emit_exact_3d_dispatch,
}


def emit_plan_materialization(lines, route, definition, context):
    route_id = route_validator.require_string(route, "id", "route")
    route_constant = route_id_constant(route_id)
    invocation = route_validator.require_dict(route, "invocation", "route")
    buffers = sorted(route_validator.require_array(invocation, "buffers", "route"), key=lambda item: item["position"])
    scalars = sorted(route_validator.require_array(invocation, "scalars", "route"), key=lambda item: item["position"])
    dispatch = route_validator.require_dict(invocation, "dispatch", "route")
    abi = route_validator.require_dict(definition, "abi", "definition")
    constant_byte_length = route_validator.require_int(abi, "constant_byte_length", "definition")
    offsets, constants_size = scalar_offsets(scalars, "route")
    if constants_size != constant_byte_length:
        raise ValueError(f"route scalar size {constants_size} does not match definition constant bytes {constant_byte_length}")

    lines.append(PLAN_SETUP_TEMPLATE.format(route_id_constant=route_constant))

    for buffer in buffers:
        position = route_validator.require_int(buffer, "position", "route")
        tensor = route_validator.require_string(buffer, "tensor", "route")
        lines.append(BIND_BUFFER_TEMPLATE.format(
            tensor=role_var(tensor),
            position=position,
            route_id_constant=route_constant,
        ))
    lines.append(f"    plan->binding_count = {len(buffers)};")

    for scalar, offset in zip(scalars, offsets):
        name = route_validator.require_string(scalar, "name", "route")
        scalar_type = route_validator.require_string(scalar, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        if "source" in scalar:
            value = typed_expr(source_expr(route_validator.require_string(scalar, "source", "route")), scalar_type)
        else:
            value = scalar_literal(scalar["value"], scalar_type)
        temp = f"constant_{c_identifier(name)}"
        lines.append(PACK_SCALAR_TEMPLATE.format(
            cpp_type=cpp_type,
            name=temp,
            value=value,
            offset=offset,
        ))
    lines.append(f"    plan->constants_size = {constant_byte_length};")

    kind = route_validator.require_string(dispatch, "kind", "route")
    emitter = DISPATCH_EMITTERS.get(kind)
    if emitter is None:
        raise ValueError(f"unsupported dispatch kind {kind}")
    lines.extend(emitter(dispatch, context, route_constant))

    lines.extend([
        f"    return ggml_backend_hrx_hsaco_supported({route_constant});",
    ])


def generate_route_impl(route_path, route, definition):
    validate_attribute_indices(route, route_path)

    match = route_validator.require_dict(route, "match", route_path)
    op = route_validator.require_string(match, "op", f"{route_path}: match")
    op_rule = route_validator.OP_RULES[op]
    route_id = route_validator.require_string(route, "id", route_path)
    function_name = f"ggml_backend_hrx_hsaco_route_{c_identifier(route_id)}"
    route_constant = route_id_constant(route_id)
    context = route_validator.RouteContext(
        route_path,
        op_rule,
        route_validator.require_dict(match, "tensors", route_path),
        match.get("attributes", {}),
        route_validator.require_dict(route, "derived", route_path),
    )

    lines = []
    emit_header(lines, route)
    lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
        function_name=function_name,
        op=op,
        route_id_constant=route_constant,
    ))
    emit_tensor_setup(lines, route, op_rule)
    emit_dtype_checks(lines, route)
    emit_attributes(lines, route)
    emit_derived(lines, route, context)
    emit_predicates(lines, route, context)
    emit_plan_materialization(lines, route, definition, context)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", default=str(route_validator.default_source_root()))
    parser.add_argument("--route", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    try:
        route_path, route, _, definition = load_route(Path(args.source_root), args.route)
        output = generate_route_impl(route_path, route, definition)
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as err:
        print(f"ValueError: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
