#!/usr/bin/env python3

import argparse
import json
import sys
from pathlib import Path

from utils import hrx_route_emit as route_emit
from utils import hrx_route_schema as route_schema
import validate_loom_routes as route_validator



ATTRIBUTE_INDICES = route_emit.ATTRIBUTE_INDICES
CPP_SCALAR_TYPES = route_emit.CPP_SCALAR_TYPES
MAX_CONSUMED_NODES = 24

UNSUPPORTED_REASON_BY_PREDICATE = {
    "contiguous": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "same_shape": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "same_layout": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "same_storage_span": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "rank": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "field": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "src_absent": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "src_present": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "elided": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "no_overlap": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
}

ROUTE_FUNCTION_OPEN_TEMPLATE = """static ggml_backend_hrx_loom_op_response {function_name}(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {{
    if (!catalog || !request || !request->op) {{
        return ggml_backend_hrx_loom_failed(nullptr);
    }}
    const ggml_tensor * node = request->op;
    if (node->op != {op}) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }}
    const ggml_backend_hrx_loom_catalog_entry * entry = ggml_backend_hrx_loom_find_entry(catalog, {route_id_constant});
    if (!entry) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_TARGET);
    }}"""

MULTI_STEP_ROUTE_FUNCTION_OPEN_TEMPLATE = """static ggml_backend_hrx_loom_op_response {function_name}(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {{
    if (!catalog || !request || !request->op) {{
        return ggml_backend_hrx_loom_failed(nullptr);
    }}
    const ggml_tensor * node = request->op;
    if (node->op != {op}) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }}"""

PLAN_SETUP_TEMPLATE = """
    std::memset(plan, 0, sizeof(*plan));
    plan->route_id = {route_id_constant};
    plan->consumed_node_count = 1;
    plan->consumed_node_indices[0] = request->node_index;"""

MULTI_STEP_PLAN_SETUP_TEMPLATE = """
    std::memset(plan, 0, sizeof(*plan));
    plan->route_id = {route_id_constant};
    plan->consumed_node_count = 1;
    plan->consumed_node_indices[0] = request->node_index;"""

BIND_BUFFER_TEMPLATE = """    {dispatch_expr}.transient_binding_indices[{position}] = -1;
    {dispatch_expr}.transient_binding_accesses[{position}] = GGML_BACKEND_HRX_LOOM_BUFFER_ACCESS_NONE;
    if (!ggml_backend_hrx_loom_bind_tensor(request, {tensor}, &{dispatch_expr}.bindings[{position}])) {{
        return ggml_backend_hrx_loom_failed({route_id_constant});
    }}"""

PACK_SCALAR_TEMPLATE = """    const {cpp_type} {name} = {value};
    std::memcpy(plan->constants + {offset}, &{name}, sizeof({name}));"""

DISPATCHER_CPP_HEADER_TEMPLATE = """// Generated by generate_loom_route_impl.py.

#include "loom-catalog/ggml-hrx-loom-catalog-runtime-internal.h"

#include <algorithm>
#include <cstdlib>
#include <cstdio>
#include <cstring>

[[maybe_unused]] static int64_t ggml_backend_hrx_loom_tensor_permutation_axis(const ggml_tensor * tensor, const int axis) {
    int order[4] = {0, 1, 2, 3};
    for (int i = 1; i < 4; ++i) {
        const int value = order[i];
        int j = i - 1;
        while (j >= 0 && tensor->nb[order[j]] > tensor->nb[value]) {
            order[j + 1] = order[j];
            --j;
        }
        order[j + 1] = value;
    }
    return axis >= 0 && axis < 4 ? order[axis] : -1;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensors_have_same_layout(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    if (!lhs || !rhs) {
        return false;
    }
    for (int i = 0; i < 4; ++i) {
        if (lhs->nb[i] != rhs->nb[i]) {
            return false;
        }
    }
    return true;
}

[[maybe_unused]] static uintptr_t ggml_backend_hrx_loom_tensor_addr(const ggml_tensor * tensor) {
    const ggml_tensor * base = tensor && tensor->view_src ? tensor->view_src : tensor;
    return base ? reinterpret_cast<uintptr_t>(base->data) + tensor->view_offs : 0;
}

[[maybe_unused]] static const void * ggml_backend_hrx_loom_tensor_buffer(const ggml_tensor * tensor) {
    const ggml_tensor * base = tensor && tensor->view_src ? tensor->view_src : tensor;
    return base ? base->buffer : nullptr;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensors_overlap(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    if (!lhs || !rhs || ggml_backend_hrx_loom_tensor_buffer(lhs) != ggml_backend_hrx_loom_tensor_buffer(rhs)) {
        return false;
    }
    const uintptr_t lhs_begin = ggml_backend_hrx_loom_tensor_addr(lhs);
    const uintptr_t rhs_begin = ggml_backend_hrx_loom_tensor_addr(rhs);
    const uintptr_t lhs_end = lhs_begin + ggml_nbytes(lhs);
    const uintptr_t rhs_end = rhs_begin + ggml_nbytes(rhs);
    return lhs_begin < rhs_end && rhs_begin < lhs_end;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensors_have_same_storage_span(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    if (!lhs || !rhs || lhs->type != rhs->type) {
        return false;
    }
    if (ggml_backend_hrx_loom_tensor_buffer(lhs) != ggml_backend_hrx_loom_tensor_buffer(rhs)) {
        return false;
    }
    return ggml_backend_hrx_loom_tensor_addr(lhs) == ggml_backend_hrx_loom_tensor_addr(rhs) &&
           ggml_nbytes(lhs) == ggml_nbytes(rhs);
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_node_index_is_matched(
        const int * matched_node_indices,
        int matched_node_count,
        int node_index) {
    if (!matched_node_indices || node_index < 0) {
        return false;
    }
    for (int i = 0; i < matched_node_count; ++i) {
        if (matched_node_indices[i] == node_index) {
            return true;
        }
    }
    return false;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensor_is_transient(
        const ggml_backend_hrx_loom_op_request * request,
        const ggml_tensor * tensor,
        const int * matched_node_indices,
        int matched_node_count) {
    if (!request || !request->cgraph || !tensor || !matched_node_indices || matched_node_count <= 0) {
        return false;
    }
    bool consumed_inside = false;
    for (int i = 0; i < request->cgraph->n_nodes; ++i) {
        const bool inside = ggml_backend_hrx_loom_node_index_is_matched(matched_node_indices, matched_node_count, i);
        const ggml_tensor * node = request->cgraph->nodes[i];
        if (!node) {
            continue;
        }
        for (int j = 0; j < GGML_MAX_SRC; ++j) {
            if (node->src[j] != tensor) {
                continue;
            }
            if (inside) {
                consumed_inside = true;
            } else {
                return false;
            }
        }
    }
    return consumed_inside;
}
"""

DISPATCHER_FUNCTION_OPEN_TEMPLATE = """ggml_backend_hrx_loom_op_response ggml_backend_hrx_loom_match_or_prepare_request(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {
    if (!catalog || !request || !request->op) {
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }

    switch (request->op->op) {"""

DISPATCHER_FUNCTION_CLOSE_TEMPLATE = """        default:
            break;
    }
    return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
}
"""

REORDER_DISPATCHER_FUNCTION_OPEN_TEMPLATE = """ggml_backend_hrx_loom_op_response ggml_backend_hrx_loom_match_reorder_request(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {
    if (!catalog || !request || !request->op || !plan) {
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }

    switch (request->op->op) {"""


cpp_string = route_emit.cpp_string


def c_identifier(value):
    return route_emit.c_identifier(value)


def route_function_name(route_id):
    return f"ggml_backend_hrx_loom_route_{c_identifier(route_id)}"


def op_router_function_name(op):
    op_name = op
    if op_name.startswith("GGML_OP_"):
        op_name = op_name[len("GGML_OP_"):]
    return f"ggml_backend_hrx_loom_router_{c_identifier(op_name).lower()}"


def route_id_constant(route_id):
    return f"GGML_HRX_LOOM_ROUTE_ID_{c_identifier(route_id).upper()}"


def step_entry_constant(route_id, step_name):
    return route_id_constant(f"{route_id}::{step_name}")


def route_entry_constant(route_id, dispatches, index):
    if len(dispatches) == 1:
        return route_id_constant(route_id)
    dispatch_name = route_schema.require_string(dispatches[index], "name", "route")
    return step_entry_constant(route_id, dispatch_name)


def route_response(reason):
    return f"return ggml_backend_hrx_loom_unsupported({reason});"


def failed_response(route_constant):
    return f"return ggml_backend_hrx_loom_failed({route_constant});"


def load_route(source_root, route_name):
    source_root = source_root.resolve()
    route_path = Path(route_name)
    if not route_path.is_absolute():
        route_path = source_root / route_path
    route_path = route_path.resolve()

    metadata_targets = route_validator.load_metadata_targets(source_root)
    definitions = route_validator.load_definitions(source_root)
    route_validator.validate_route(route_path, definitions, metadata_targets)
    route = route_schema.read_json(route_path)
    dispatches = route_validator.route_dispatches(route, route_path)
    dispatch_definitions = route_validator.resolve_dispatch_definitions(route, route_path, definitions)
    if len(dispatches) > 1:
        return route_path, route, None, dispatch_definitions
    definition_path, definition = dispatch_definitions[0]
    return route_path, route, definition_path, definition


def scalar_offsets(scalars, route_path):
    return route_emit.scalar_offsets(scalars, route_path, route_schema)


def typed_expr(expr, scalar_type):
    return route_emit.typed_expr(expr, scalar_type)


def scalar_literal(value, scalar_type):
    return route_emit.scalar_literal(value, scalar_type)


def source_expr(source):
    return route_emit.source_expr(source)


def config_value_expr(binding):
    scalar_type = route_schema.require_string(binding, "type", "route")
    if "source" in binding:
        return typed_expr(source_expr(route_schema.require_string(binding, "source", "route")), scalar_type)
    return scalar_literal(binding["value"], scalar_type)


def config_format_args(value_var, scalar_type):
    if scalar_type in {"i32", "i64", "index"}:
        return '"%lld"', f"static_cast<long long>({value_var})"
    if scalar_type == "f32":
        return '"%.9g"', f"static_cast<double>({value_var})"
    if scalar_type == "f64":
        return '"%.17g"', value_var
    raise ValueError(f"unsupported config type {scalar_type}")


def config_value_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_value"


def config_text_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_text"


def config_length_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_length"


def emit_config_materialization(lines, route_dispatch):
    config = route_schema.require_dict(route_dispatch, "config", "route")
    bindings = route_schema.require_array(config, "bindings", "route")
    for binding in bindings:
        scalar_type = route_schema.require_string(binding, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        value_var = config_value_var(binding)
        text_var = config_text_var(binding)
        length_var = config_length_var(binding)
        format_text, format_value = config_format_args(value_var, scalar_type)
        lines.extend([
            f"    const {cpp_type} {value_var} = {config_value_expr(binding)};",
            f"    char {text_var}[128] = {{}};",
            f"    const int {length_var} = std::snprintf({text_var}, sizeof({text_var}), {format_text}, {format_value});",
            f"    if ({length_var} < 0 || static_cast<size_t>({length_var}) >= sizeof({text_var})) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_CONFIG);",
            "    }",
        ])


def emit_dispatch_config_plan_copy(lines, route_dispatch, dispatch_expr):
    config = route_schema.require_dict(route_dispatch, "config", "route")
    bindings = route_schema.require_array(config, "bindings", "route")
    for i, binding in enumerate(bindings):
        name = route_schema.require_string(binding, "name", "route")
        scalar_type = route_schema.require_string(binding, "type", "route")
        text_var = config_text_var(binding)
        lines.extend([
            f"    std::memcpy({dispatch_expr}.config_bindings[{i}].name, {cpp_string(name)}, sizeof({cpp_string(name)}));",
            f"    std::memcpy({dispatch_expr}.config_bindings[{i}].value, {text_var}, static_cast<size_t>({config_length_var(binding)}) + 1);",
            f"    {dispatch_expr}.config_bindings[{i}].type = {cpp_string(scalar_type)};",
        ])
    lines.append(f"    {dispatch_expr}.config_binding_count = {len(bindings)};")


def emit_step_config_plan_copy(lines, step, step_expr):
    emit_dispatch_config_plan_copy(lines, step, step_expr)


def emit_integer_operand(value, context):
    return route_emit.emit_integer_operand(value, context, route_schema)


def transient_access(kind):
    if kind == "input":
        return "GGML_BACKEND_HRX_LOOM_BUFFER_ACCESS_READ"
    if kind == "output":
        return "GGML_BACKEND_HRX_LOOM_BUFFER_ACCESS_WRITE"
    if kind == "inout":
        return "GGML_BACKEND_HRX_LOOM_BUFFER_ACCESS_READ_WRITE"
    raise ValueError(f"unsupported buffer kind {kind}")


def graph_transient_indices(dispatches, base_index=0):
    indices = {}
    next_index = base_index
    for dispatch in dispatches:
        for buffer in route_schema.require_array(dispatch, "buffers", "route"):
            if buffer.get("storage") != "graph_transient":
                continue
            tensor = route_schema.require_string(buffer, "tensor", "route")
            if tensor not in indices:
                indices[tensor] = next_index
                next_index += 1
    return indices


def emit_graph_transient_materialization(lines, graph_indices, route_constant):
    for tensor, transient_index in graph_indices.items():
        tensor_expr = route_emit.role_var(tensor)
        lines.extend([
            f"    plan->transients[{transient_index}].graph_tensor = {tensor_expr};",
            f"    plan->transients[{transient_index}].size = ggml_nbytes({tensor_expr});",
            f"    if (plan->transients[{transient_index}].size == 0) {{",
            f"        return ggml_backend_hrx_loom_failed({route_constant});",
            "    }",
        ])


def emit_graph_transient_binding(lines, dispatch_expr, position, kind, tensor, transient_index):
    tensor_expr = route_emit.role_var(tensor)
    access = transient_access(kind)
    lines.extend([
        f"    {dispatch_expr}.transient_binding_indices[{position}] = {transient_index};",
        f"    {dispatch_expr}.transient_binding_accesses[{position}] = {access};",
        f"    {dispatch_expr}.bindings[{position}].length = ggml_nbytes({tensor_expr});",
    ])


def emit_plan_materialization(lines, route, definition, context, consumed_node_indices=None):
    route_id = route_schema.require_string(route, "id", "route")
    route_constant = route_id_constant(route_id)
    dispatches = route_schema.require_list(route, "dispatches", "route")
    route_dispatch = dispatches[0]
    graph_indices = graph_transient_indices(dispatches)
    if len(graph_indices) > 4:
        raise ValueError("route has too many transient buffers")
    buffers = sorted(route_schema.require_array(route_dispatch, "buffers", "route"), key=lambda item: item["position"])
    scalars = sorted(route_schema.require_array(route_dispatch, "scalars", "route"), key=lambda item: item["position"])
    dispatch = route_schema.require_dict(route_dispatch, "dispatch", "route")
    abi = route_schema.require_dict(definition, "abi", "definition")
    constant_byte_length = route_schema.require_int(abi, "constant_byte_length", "definition")
    offsets, constants_size = scalar_offsets(scalars, "route")
    if constants_size != constant_byte_length:
        raise ValueError(f"route scalar size {constants_size} does not match definition constant bytes {constant_byte_length}")

    dispatch_expr = "plan->dispatches[0]"
    lines.extend([
        "    if (ggml_backend_hrx_loom_match_only(plan)) {",
        f"        return ggml_backend_hrx_loom_supported({route_constant});",
        "    }",
    ])
    lines.append(PLAN_SETUP_TEMPLATE.format(route_id_constant=route_constant))
    if consumed_node_indices is not None:
        if len(consumed_node_indices) > MAX_CONSUMED_NODES:
            raise ValueError(f"route consumes too many graph nodes: {len(consumed_node_indices)}")
        lines.append(f"    plan->consumed_node_count = {len(consumed_node_indices)};")
        for i, node_index in enumerate(consumed_node_indices):
            lines.append(f"    plan->consumed_node_indices[{i}] = {node_index};")
    lines.extend([
        "    if (ggml_backend_hrx_loom_reorder_match(request, plan)) {",
        f"        return ggml_backend_hrx_loom_supported({route_constant});",
        "    }",
        "    if (!request->stream || !request->bind_tensor) {",
        f"        return ggml_backend_hrx_loom_failed({route_constant});",
        "    }",
    ])
    emit_graph_transient_materialization(lines, graph_indices, route_constant)
    if graph_indices:
        lines.append(f"    plan->transient_count = {len(graph_indices)};")
    lines.extend([
        f"    {dispatch_expr}.entry = entry;",
        "    plan->dispatch_count = 1;",
    ])
    emit_config_materialization(lines, route_dispatch)
    emit_dispatch_config_plan_copy(lines, route_dispatch, dispatch_expr)

    for buffer in buffers:
        position = route_schema.require_int(buffer, "position", "route")
        tensor = route_schema.require_string(buffer, "tensor", "route")
        if buffer.get("storage") == "graph_transient":
            emit_graph_transient_binding(
                lines,
                dispatch_expr,
                position,
                route_schema.require_string(buffer, "kind", "route"),
                tensor,
                graph_indices[tensor],
            )
        else:
            lines.append(BIND_BUFFER_TEMPLATE.format(
                dispatch_expr=dispatch_expr,
                tensor=route_emit.role_var(tensor),
                position=position,
                route_id_constant=route_constant,
            ))
    lines.append(f"    {dispatch_expr}.binding_count = {len(buffers)};")

    for scalar, offset in zip(scalars, offsets):
        name = route_schema.require_string(scalar, "name", "route")
        scalar_type = route_schema.require_string(scalar, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        if "source" in scalar:
            value = typed_expr(source_expr(route_schema.require_string(scalar, "source", "route")), scalar_type)
        else:
            value = scalar_literal(scalar["value"], scalar_type)
        temp = f"constant_{c_identifier(name)}"
        lines.append(PACK_SCALAR_TEMPLATE.format(
            cpp_type=cpp_type,
            name=temp,
            value=value,
            offset=offset,
        ).replace("plan->constants", f"{dispatch_expr}.constants"))
    lines.append(f"    {dispatch_expr}.constants_size = {constant_byte_length};")

    dispatch_lines = route_emit.emit_dispatch_config(dispatch, context, route_constant, failed_response, route_schema)
    lines.extend([
        line.replace("plan->dispatch", f"{dispatch_expr}.dispatch")
            .replace("entry->workgroup_size", f"{dispatch_expr}.entry->workgroup_size")
        for line in dispatch_lines
    ])

    lines.append(f"    return ggml_backend_hrx_loom_supported({route_constant});")


def emit_step_materialization(lines, route_id, dispatches, step_index, step, definition, context, transient_indices):
    route_constant = route_id_constant(route_id)
    entry_constant = route_entry_constant(route_id, dispatches, step_index)
    step_expr = f"plan->dispatches[{step_index}]"
    buffers = sorted(route_schema.require_array(step, "buffers", "route"), key=lambda item: item["position"])
    scalars = sorted(route_schema.require_array(step, "scalars", "route"), key=lambda item: item["position"])
    dispatch = route_schema.require_dict(step, "dispatch", "route")
    abi = route_schema.require_dict(definition, "abi", "definition")
    constant_byte_length = route_schema.require_int(abi, "constant_byte_length", "definition")
    offsets, constants_size = scalar_offsets(scalars, "route")
    if constants_size != constant_byte_length:
        raise ValueError(f"step scalar size {constants_size} does not match definition constant bytes {constant_byte_length}")

    lines.extend([
        f"    const ggml_backend_hrx_loom_catalog_entry * step_{step_index}_entry = ggml_backend_hrx_loom_find_entry(catalog, {entry_constant});",
        f"    if (!step_{step_index}_entry) {{",
        "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_TARGET);",
        "    }",
        f"    {step_expr}.entry = step_{step_index}_entry;",
    ])
    emit_step_config_plan_copy(lines, step, step_expr)

    for buffer in buffers:
        position = route_schema.require_int(buffer, "position", "route")
        if "tensor" in buffer:
            tensor = route_schema.require_string(buffer, "tensor", "route")
            if buffer.get("storage") == "graph_transient":
                emit_graph_transient_binding(
                    lines,
                    step_expr,
                    position,
                    route_schema.require_string(buffer, "kind", "route"),
                    tensor,
                    transient_indices[tensor],
                )
            else:
                lines.extend([
                    f"    {step_expr}.transient_binding_indices[{position}] = -1;",
                    f"    {step_expr}.transient_binding_accesses[{position}] = GGML_BACKEND_HRX_LOOM_BUFFER_ACCESS_NONE;",
                    f"    if (!ggml_backend_hrx_loom_bind_tensor(request, {route_emit.role_var(tensor)}, &{step_expr}.bindings[{position}])) {{",
                    f"        return ggml_backend_hrx_loom_failed({route_constant});",
                    "    }",
                ])
        else:
            transient = route_schema.require_string(buffer, "transient", "route")
            transient_index = transient_indices[transient]
            lines.extend([
                f"    {step_expr}.transient_binding_indices[{position}] = {transient_index};",
                f"    {step_expr}.transient_binding_accesses[{position}] = {transient_access(route_schema.require_string(buffer, 'kind', 'route'))};",
                f"    {step_expr}.bindings[{position}].offset = plan->transients[{transient_index}].offset;",
                f"    {step_expr}.bindings[{position}].length = plan->transients[{transient_index}].size;",
            ])
    lines.append(f"    {step_expr}.binding_count = {len(buffers)};")

    for scalar, offset in zip(scalars, offsets):
        name = route_schema.require_string(scalar, "name", "route")
        scalar_type = route_schema.require_string(scalar, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        if "source" in scalar:
            value = typed_expr(source_expr(route_schema.require_string(scalar, "source", "route")), scalar_type)
        else:
            value = scalar_literal(scalar["value"], scalar_type)
        temp = f"step_{step_index}_constant_{c_identifier(name)}"
        lines.append(PACK_SCALAR_TEMPLATE.format(
            cpp_type=cpp_type,
            name=temp,
            value=value,
            offset=offset,
        ).replace("plan->constants", f"{step_expr}.constants"))
    lines.append(f"    {step_expr}.constants_size = {constant_byte_length};")

    dispatch_lines = route_emit.emit_dispatch_config(dispatch, context, route_constant, failed_response, route_schema)
    lines.append("    {")
    lines.extend([
        line.replace("plan->dispatch", f"{step_expr}.dispatch")
            .replace("entry->workgroup_size", f"{step_expr}.entry->workgroup_size")
        for line in dispatch_lines
    ])
    lines.append("    }")


def emit_multi_step_plan_materialization(lines, route, step_definitions, context, consumed_node_indices=None):
    route_id = route_schema.require_string(route, "id", "route")
    route_constant = route_id_constant(route_id)
    transient_buffers = route.get("transient_buffers", {})
    steps = route_schema.require_list(route, "dispatches", "route")
    if len(transient_buffers) > 4:
        raise ValueError("route has too many transient buffers")
    if len(steps) > 5:
        raise ValueError("route has too many dispatches")
    graph_indices = graph_transient_indices(steps, len(transient_buffers))
    if len(transient_buffers) + len(graph_indices) > 4:
        raise ValueError("route has too many transient buffers")

    lines.extend([
        "    if (ggml_backend_hrx_loom_match_only(plan)) {",
        f"        return ggml_backend_hrx_loom_supported({route_constant});",
        "    }",
    ])
    lines.append(MULTI_STEP_PLAN_SETUP_TEMPLATE.format(route_id_constant=route_constant))
    if consumed_node_indices is not None:
        if len(consumed_node_indices) > MAX_CONSUMED_NODES:
            raise ValueError(f"route consumes too many graph nodes: {len(consumed_node_indices)}")
        lines.append(f"    plan->consumed_node_count = {len(consumed_node_indices)};")
        for i, node_index in enumerate(consumed_node_indices):
            lines.append(f"    plan->consumed_node_indices[{i}] = {node_index};")
    lines.extend([
        "    if (ggml_backend_hrx_loom_reorder_match(request, plan)) {",
        f"        return ggml_backend_hrx_loom_supported({route_constant});",
        "    }",
        "    if (!request->stream || !request->bind_tensor) {",
        f"        return ggml_backend_hrx_loom_failed({route_constant});",
        "    }",
    ])

    transient_indices = {}
    lines.append("    size_t transient_cursor = 0;")
    for i, (name, transient) in enumerate(transient_buffers.items()):
        size_expr = emit_integer_operand(transient["size"], context)
        transient_indices[name] = i
        lines.extend([
            "    if (!ggml_backend_hrx_loom_align_size(transient_cursor, GGML_BACKEND_HRX_LOOM_TRANSIENT_ALIGNMENT, &transient_cursor)) {",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_CONFIG);",
            "    }",
            f"    const int64_t transient_{i}_size_value = {size_expr};",
            f"    if (transient_{i}_size_value <= 0) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_CONFIG);",
            "    }",
            f"    const size_t transient_{i}_size = static_cast<size_t>(transient_{i}_size_value);",
            f"    plan->transients[{i}].offset = transient_cursor;",
            f"    plan->transients[{i}].size = transient_{i}_size;",
            f"    if (!ggml_backend_hrx_loom_checked_add_size(transient_cursor, transient_{i}_size, &transient_cursor)) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_CONFIG);",
            "    }",
        ])
    lines.append(f"    plan->transient_count = {len(transient_buffers)};")
    lines.append("    plan->transient_byte_length = transient_cursor;")

    for tensor, transient_index in graph_indices.items():
        transient_indices[tensor] = transient_index
    emit_graph_transient_materialization(lines, graph_indices, route_constant)
    if graph_indices:
        lines.append(f"    plan->transient_count = {len(transient_buffers) + len(graph_indices)};")

    lines.append(f"    plan->dispatch_count = {len(steps)};")
    for i, step in enumerate(steps):
        lines.append("    {")
        emit_config_materialization(lines, step)
        _, definition = step_definitions[i]
        emit_step_materialization(lines, route_id, steps, i, step, definition, context, transient_indices)
        lines.append("    }")

    lines.append(f"    return ggml_backend_hrx_loom_supported({route_constant});")


def fusion_op_var(op_name):
    return f"{c_identifier(op_name)}_op"


def fusion_role_expr(op_var, role):
    if role == "dst":
        return op_var
    if role.startswith("src") and role[3:].isdigit():
        return f"{op_var}->src[{int(role[3:])}]"
    raise ValueError(f"unsupported tensor role {role}")


def emit_fusion_tensor_role_assignments(lines, op_var, op_tensors):
    for role, tensor_name in op_tensors.items():
        expr = fusion_role_expr(op_var, role)
        tensor_var = route_emit.role_var(tensor_name)
        lines.extend([
            f"        if ({tensor_var} && {tensor_var} != {expr}) {{",
            "            return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE);",
            "        }",
            f"        {tensor_var} = {expr};",
        ])


def emit_fusion_op_setup(lines, route, route_constant):
    match = route_schema.require_dict(route, "match", "route")
    ops = route_schema.require_dict(match, "ops", "route")
    op_names = list(ops)
    matched_node_count = len(op_names)
    reorder_enabled = match.get("reorder", False)
    lines.extend([
        f"    static constexpr int matched_node_count = {matched_node_count};",
        "    const bool reorder_match = ggml_backend_hrx_loom_reorder_match(request, plan);",
        f"    if (reorder_match && {'false' if reorder_enabled else 'true'}) {{",
        "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "    }",
        "    if (!request->cgraph || request->node_index < 0 || request->node_index >= request->cgraph->n_nodes ||",
        "            request->cgraph->nodes[request->node_index] != node) {",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "    }",
        "    int matched_node_indices[matched_node_count] = {};",
        "    for (int i = 0; i < matched_node_count; ++i) {",
        "        matched_node_indices[i] = -1;",
        "    }",
    ])
    for op_name in op_names:
        lines.append(f"    const ggml_tensor * {fusion_op_var(op_name)} = nullptr;")
    for tensor_name in sorted(route_schema.route_tensors(route, "route")):
        lines.append(f"    const ggml_tensor * {route_emit.role_var(tensor_name)} = nullptr;")

    first_op_name = op_names[0]
    first_op = route_schema.require_string(ops[first_op_name], "op", "route")
    first_op_var = fusion_op_var(first_op_name)
    lines.extend([
        f"    {first_op_var} = node;",
        f"    if (!{first_op_var} || {first_op_var}->op != {first_op}) {{",
        "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "    }",
        "    matched_node_indices[0] = request->node_index;",
        "    {",
    ])
    emit_fusion_tensor_role_assignments(
        lines,
        first_op_var,
        route_schema.require_dict(ops[first_op_name], "tensors", "route"),
    )
    lines.append("    }")

    for i, op_name in enumerate(op_names[1:], 1):
        op_tensors = route_schema.require_dict(ops[op_name], "tensors", "route")
        op = route_schema.require_string(ops[op_name], "op", "route")
        op_var = fusion_op_var(op_name)
        lines.extend([
            "    if (reorder_match) {",
            "        for (int candidate_index = request->node_index + 1; candidate_index < request->cgraph->n_nodes; ++candidate_index) {",
            "            if (ggml_backend_hrx_loom_node_index_is_matched(matched_node_indices, matched_node_count, candidate_index)) {",
            "                continue;",
            "            }",
            "            const ggml_tensor * candidate = request->cgraph->nodes[candidate_index];",
            f"            if (!candidate || candidate->op != {op}) {{",
            "                continue;",
            "            }",
            "            bool candidate_ok = true;",
        ])
        for role, tensor_name in op_tensors.items():
            expr = fusion_role_expr("candidate", role)
            tensor_var = route_emit.role_var(tensor_name)
            lines.extend([
                f"            if ({tensor_var} && {tensor_var} != {expr}) {{",
                "                candidate_ok = false;",
                "            }",
            ])
        lines.extend([
            "            if (!candidate_ok) {",
            "                continue;",
            "            }",
            f"            {op_var} = candidate;",
            f"            matched_node_indices[{i}] = candidate_index;",
            "            break;",
            "        }",
            "    } else {",
            f"        if (request->node_index + {i} >= request->cgraph->n_nodes) {{",
            "            return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "        }",
            f"        {op_var} = request->cgraph->nodes[request->node_index + {i}];",
            f"        if (!{op_var} || {op_var}->op != {op}) {{",
            "            return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "        }",
            f"        matched_node_indices[{i}] = request->node_index + {i};",
            "    }",
            f"    if (!{op_var}) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "    }",
            "    {",
        ])
        emit_fusion_tensor_role_assignments(lines, op_var, op_tensors)
        lines.append("    }")

    tensors = route_schema.route_tensors(route, "route")
    required = sorted(name for name, tensor in tensors.items() if not tensor.get("optional", False))
    if required:
        condition = " || ".join([f"!{route_emit.role_var(name)}" for name in required])
        lines.extend([
            f"    if ({condition}) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE);",
            "    }",
        ])


def emit_fusion_attributes(lines, route):
    match = route_schema.require_dict(route, "match", "route")
    ops = route_schema.require_dict(match, "ops", "route")
    for op_name, op_match in ops.items():
        op = route_schema.require_string(op_match, "op", "route")
        attributes = op_match.get("attributes", {})
        if not attributes:
            continue
        indices = ATTRIBUTE_INDICES[op]
        op_var = fusion_op_var(op_name)
        for name, attr in attributes.items():
            scalar_type = route_schema.require_string(attr, "type", "route")
            getter = route_emit.ATTRIBUTE_GETTERS[scalar_type]
            cast = CPP_SCALAR_TYPES[scalar_type]
            lines.append(f"    const {cast} {route_emit.fusion_attribute_var(op_name, name)} = {getter}({op_var}, {indices[name]});")


def generate_fusion_route_impl(route_path, route, definition):
    match = route_schema.require_dict(route, "match", route_path)
    ops = route_schema.require_dict(match, "ops", route_path)
    anchors = match.get("anchors", [])
    anchor_name = anchors[0] if anchors else next(iter(ops))
    anchor_op = route_schema.require_string(ops[anchor_name], "op", route_path)
    route_id = route_schema.require_string(route, "id", route_path)
    function_name = route_function_name(route_id)
    route_constant = route_id_constant(route_id)
    dispatches = route_schema.require_list(route, "dispatches", route_path)
    has_multiple_dispatches = len(dispatches) > 1
    context = route_schema.FusionRouteContext(
        route_path,
        route_schema.route_tensors(route, route_path),
        {op_name: op_match.get("attributes", {}) for op_name, op_match in ops.items()},
        route_schema.require_dict(route, "derived", route_path),
    )

    lines = []
    if has_multiple_dispatches:
        lines.append(MULTI_STEP_ROUTE_FUNCTION_OPEN_TEMPLATE.format(
            function_name=function_name,
            op=anchor_op,
        ))
    else:
        lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
            function_name=function_name,
            op=anchor_op,
            route_id_constant=route_constant,
        ))
    emit_fusion_op_setup(lines, route, route_constant)
    route_emit.emit_dtype_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_DTYPE",
    )
    emit_fusion_attributes(lines, route)
    route_emit.emit_shape_captures(lines, route, route_schema)
    route_emit.emit_tensor_declaration_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    )
    route_emit.emit_derived(lines, route, context, route_schema, "ggml_backend_hrx_loom_next_power_of_2")
    route_emit.emit_predicates(lines, route, context, route_schema, UNSUPPORTED_REASON_BY_PREDICATE, route_response)
    if has_multiple_dispatches:
        emit_multi_step_plan_materialization(
            lines,
            route,
            definition,
            context,
            [f"matched_node_indices[{i}]" for i in range(len(ops))],
        )
    else:
        emit_plan_materialization(
            lines,
            route,
            definition,
            context,
            [f"matched_node_indices[{i}]" for i in range(len(ops))],
        )
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_route_impl(route_path, route, definition):
    route_emit.validate_attribute_indices(route, route_path, route_schema, ATTRIBUTE_INDICES)
    if route_schema.route_is_fusion_v2(route, route_path):
        return generate_fusion_route_impl(route_path, route, definition)

    match = route_schema.require_dict(route, "match", route_path)
    op = route_schema.require_string(match, "op", f"{route_path}: match")
    op_rule = route_schema.OP_RULES[op]
    route_id = route_schema.require_string(route, "id", route_path)
    function_name = route_function_name(route_id)
    route_constant = route_id_constant(route_id)
    dispatches = route_schema.require_list(route, "dispatches", route_path)
    has_multiple_dispatches = len(dispatches) > 1
    context = route_schema.RouteContext(
        route_path,
        op_rule,
        route_schema.route_tensors(route, route_path),
        match.get("attributes", {}),
        route_schema.require_dict(route, "derived", route_path),
    )

    lines = []
    if has_multiple_dispatches:
        lines.append(MULTI_STEP_ROUTE_FUNCTION_OPEN_TEMPLATE.format(
            function_name=function_name,
            op=op,
        ))
    else:
        lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
            function_name=function_name,
            op=op,
            route_id_constant=route_constant,
        ))
    lines.extend([
        "    if (ggml_backend_hrx_loom_reorder_match(request, plan)) {",
        "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "    }",
    ])
    route_emit.emit_tensor_setup(
        lines,
        route,
        op_rule,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    )
    route_emit.emit_dtype_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_DTYPE",
    )
    route_emit.emit_attributes(lines, route, route_schema, ATTRIBUTE_INDICES)
    route_emit.emit_shape_captures(lines, route, route_schema)
    route_emit.emit_tensor_declaration_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    )
    route_emit.emit_derived(lines, route, context, route_schema, "ggml_backend_hrx_loom_next_power_of_2")
    route_emit.emit_predicates(lines, route, context, route_schema, UNSUPPORTED_REASON_BY_PREDICATE, route_response)
    if has_multiple_dispatches:
        emit_multi_step_plan_materialization(lines, route, definition, context)
    else:
        emit_plan_materialization(lines, route, definition, context)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_dispatcher_impl(routes):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]
    route_infos = route_emit.route_infos_for_dispatcher(routes, route_schema)
    ops = route_emit.ops_from_route_infos(route_infos)

    for op in ops:
        lines.extend([
            f"ggml_backend_hrx_loom_op_response {op_router_function_name(op)}(",
            "        ggml_backend_hrx_loom_catalog * catalog,",
            "        const ggml_backend_hrx_loom_op_request * request,",
            "        ggml_backend_hrx_loom_execution_plan * plan);",
            "",
        ])

    lines.append(DISPATCHER_FUNCTION_OPEN_TEMPLATE)
    for op in ops:
        lines.extend([
            f"        case {op}:",
            f"            return {op_router_function_name(op)}(catalog, request, plan);",
        ])
    lines.append(DISPATCHER_FUNCTION_CLOSE_TEMPLATE)
    lines.append(REORDER_DISPATCHER_FUNCTION_OPEN_TEMPLATE)
    for op in ops:
        lines.extend([
            f"        case {op}:",
            f"            return {op_router_function_name(op)}(catalog, request, plan);",
        ])
    lines.append(DISPATCHER_FUNCTION_CLOSE_TEMPLATE)
    return "\n".join(lines)


def generate_op_router_impl(routes, selected_op):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]

    route_infos = route_emit.route_infos_for_op(routes, selected_op, route_schema)
    if not route_infos:
        raise ValueError(f"no routes found for {selected_op}")

    for _, _, route_path, route, definition in route_infos:
        route_id = route_schema.require_string(route, "id", route_path)
        lines.extend([
            f"static constexpr const char * {route_id_constant(route_id)} = {cpp_string(route_id)};",
            "",
        ])
        dispatches = route_schema.require_list(route, "dispatches", route_path)
        if len(dispatches) > 1:
            for step in dispatches:
                step_name = route_schema.require_string(step, "name", route_path)
                step_entry_id = f"{route_id}::{step_name}"
                lines.extend([
                    f"static constexpr const char * {step_entry_constant(route_id, step_name)} = {cpp_string(step_entry_id)};",
                    "",
                ])
        lines.append(generate_route_impl(route_path, route, definition))

    function_name = op_router_function_name(selected_op)
    lines.extend([
        f"ggml_backend_hrx_loom_op_response {function_name}(",
        "        ggml_backend_hrx_loom_catalog * catalog,",
        "        const ggml_backend_hrx_loom_op_request * request,",
        "        ggml_backend_hrx_loom_execution_plan * plan);",
        "",
        f"ggml_backend_hrx_loom_op_response {function_name}(",
        "        ggml_backend_hrx_loom_catalog * catalog,",
        "        const ggml_backend_hrx_loom_op_request * request,",
        "        ggml_backend_hrx_loom_execution_plan * plan) {",
        "    ggml_backend_hrx_loom_op_response fallback =",
        "        ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        '    const char * forced_route = std::getenv("GGML_HRX_LOOM_FORCE_ROUTE");',
        "",
    ])

    for _, route_id, _, _, _ in route_infos:
        route_constant = route_id_constant(route_id)
        lines.extend([
            "    {",
            f"        if (!forced_route || std::strcmp(forced_route, {route_constant}) == 0) {{",
            "            ggml_backend_hrx_loom_op_response response =",
            f"                {route_function_name(route_id)}(catalog, request, plan);",
            "            if (response.result != GGML_BACKEND_HRX_LOOM_UNSUPPORTED) {",
            "                return response;",
            "            }",
            "            if (fallback.unsupported_reason == GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE &&",
            "                response.unsupported_reason != GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE) {",
            "                fallback = response;",
            "            }",
            "        }",
            "    }",
            "",
        ])

    lines.extend([
        "    return fallback;",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", default=str(route_validator.default_source_root()))
    parser.add_argument("--route", required=True, action="append")
    parser.add_argument("--out", required=True)
    parser.add_argument("--dispatcher", action="store_true")
    parser.add_argument("--op-router", action="store_true")
    parser.add_argument("--op")
    args = parser.parse_args()

    try:
        routes = [load_route(Path(args.source_root), route_name) for route_name in args.route]
        if args.dispatcher:
            output = generate_dispatcher_impl([(route_path, route, definition) for route_path, route, _, definition in routes])
        elif args.op_router:
            if not args.op:
                raise ValueError("--op-router expects --op")
            output = generate_op_router_impl([(route_path, route, definition) for route_path, route, _, definition in routes], args.op)
        else:
            raise ValueError("expected --dispatcher or --op-router")
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as err:
        print(f"ValueError: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
