#!/usr/bin/env python3

import argparse
import json
import sys
from pathlib import Path

from utils import hrx_route_emit as route_emit
from utils import hrx_route_schema as route_schema
import validate_loom_routes as route_validator



ATTRIBUTE_INDICES = route_emit.ATTRIBUTE_INDICES
CPP_SCALAR_TYPES = route_emit.CPP_SCALAR_TYPES

UNSUPPORTED_REASON_BY_PREDICATE = {
    "contiguous": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "same_shape": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "same_layout": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "rank": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "field": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "src_absent": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "src_present": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "transients": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "no_overlap": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
}

ROUTE_FUNCTION_OPEN_TEMPLATE = """static ggml_backend_hrx_loom_op_response {function_name}(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {{
    if (!catalog || !request || !request->op) {{
        return ggml_backend_hrx_loom_failed(nullptr);
    }}
    const ggml_tensor * node = request->op;
    if (node->op != {op}) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }}
    const ggml_backend_hrx_loom_catalog_entry * entry = ggml_backend_hrx_loom_find_entry(catalog, {route_id_constant});
    if (!entry) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_TARGET);
    }}"""

PLAN_SETUP_TEMPLATE = """
    if (ggml_backend_hrx_loom_match_only(plan)) {{
        return ggml_backend_hrx_loom_supported({route_id_constant});
    }}
    if (!request->stream || !request->bind_tensor) {{
        return ggml_backend_hrx_loom_failed({route_id_constant});
    }}
    std::memset(plan, 0, sizeof(*plan));
    plan->entry = entry;
    plan->consumed_node_count = 1;
    plan->consumed_node_indices[0] = request->node_index;"""

BIND_BUFFER_TEMPLATE = """    if (!ggml_backend_hrx_loom_bind_tensor(request, {tensor}, &plan->bindings[{position}])) {{
        return ggml_backend_hrx_loom_failed({route_id_constant});
    }}"""

PACK_SCALAR_TEMPLATE = """    const {cpp_type} {name} = {value};
    std::memcpy(plan->constants + {offset}, &{name}, sizeof({name}));"""

DISPATCHER_CPP_HEADER_TEMPLATE = """// Generated by generate_loom_route_impl.py.

#include "loom-catalog/ggml-hrx-loom-catalog-runtime-internal.h"

#include <cstdio>
#include <cstring>

[[maybe_unused]] static int64_t ggml_backend_hrx_loom_tensor_permutation_axis(const ggml_tensor * tensor, const int axis) {
    int order[4] = {0, 1, 2, 3};
    for (int i = 1; i < 4; ++i) {
        const int value = order[i];
        int j = i - 1;
        while (j >= 0 && tensor->nb[order[j]] > tensor->nb[value]) {
            order[j + 1] = order[j];
            --j;
        }
        order[j + 1] = value;
    }
    return axis >= 0 && axis < 4 ? order[axis] : -1;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensors_have_same_layout(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    if (!lhs || !rhs) {
        return false;
    }
    for (int i = 0; i < 4; ++i) {
        if (lhs->nb[i] != rhs->nb[i]) {
            return false;
        }
    }
    return true;
}

[[maybe_unused]] static uintptr_t ggml_backend_hrx_loom_tensor_addr(const ggml_tensor * tensor) {
    const ggml_tensor * base = tensor && tensor->view_src ? tensor->view_src : tensor;
    return base ? reinterpret_cast<uintptr_t>(base->data) + tensor->view_offs : 0;
}

[[maybe_unused]] static const void * ggml_backend_hrx_loom_tensor_buffer(const ggml_tensor * tensor) {
    const ggml_tensor * base = tensor && tensor->view_src ? tensor->view_src : tensor;
    return base ? base->buffer : nullptr;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensors_overlap(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    if (!lhs || !rhs || ggml_backend_hrx_loom_tensor_buffer(lhs) != ggml_backend_hrx_loom_tensor_buffer(rhs)) {
        return false;
    }
    const uintptr_t lhs_begin = ggml_backend_hrx_loom_tensor_addr(lhs);
    const uintptr_t rhs_begin = ggml_backend_hrx_loom_tensor_addr(rhs);
    const uintptr_t lhs_end = lhs_begin + ggml_nbytes(lhs);
    const uintptr_t rhs_end = rhs_begin + ggml_nbytes(rhs);
    return lhs_begin < rhs_end && rhs_begin < lhs_end;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensor_is_transient(
        const ggml_backend_hrx_loom_op_request * request,
        const ggml_tensor * tensor,
        int matched_node_count) {
    if (!request || !request->cgraph || !tensor || request->node_index < 0 || matched_node_count <= 0) {
        return false;
    }
    bool consumed_inside = false;
    for (int i = 0; i < request->cgraph->n_nodes; ++i) {
        const bool inside = i >= request->node_index && i < request->node_index + matched_node_count;
        const ggml_tensor * node = request->cgraph->nodes[i];
        if (!node) {
            continue;
        }
        for (int j = 0; j < GGML_MAX_SRC; ++j) {
            if (node->src[j] != tensor) {
                continue;
            }
            if (inside) {
                consumed_inside = true;
            } else {
                return false;
            }
        }
    }
    return consumed_inside;
}
"""

DISPATCHER_FUNCTION_OPEN_TEMPLATE = """ggml_backend_hrx_loom_op_response ggml_backend_hrx_loom_match_or_prepare_request(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {
    if (!catalog || !request || !request->op) {
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }

    switch (request->op->op) {"""

DISPATCHER_FUNCTION_CLOSE_TEMPLATE = """        default:
            break;
    }
    return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
}
"""


cpp_string = route_emit.cpp_string


def c_identifier(value):
    return route_emit.c_identifier(value)


def route_function_name(route_id):
    return f"ggml_backend_hrx_loom_route_{c_identifier(route_id)}"


def op_router_function_name(op):
    op_name = op
    if op_name.startswith("GGML_OP_"):
        op_name = op_name[len("GGML_OP_"):]
    return f"ggml_backend_hrx_loom_router_{c_identifier(op_name).lower()}"


def route_id_constant(route_id):
    return f"GGML_HRX_LOOM_ROUTE_ID_{c_identifier(route_id).upper()}"


def route_response(reason):
    return f"return ggml_backend_hrx_loom_unsupported({reason});"


def failed_response(route_constant):
    return f"return ggml_backend_hrx_loom_failed({route_constant});"


def load_route(source_root, route_name):
    source_root = source_root.resolve()
    route_path = Path(route_name)
    if not route_path.is_absolute():
        route_path = source_root / route_path
    route_path = route_path.resolve()

    metadata_targets = route_validator.load_metadata_targets(source_root)
    definitions = route_validator.load_definitions(source_root)
    route_validator.validate_route(route_path, definitions, metadata_targets)
    route = route_schema.read_json(route_path)
    definition_path = (route_path.parent / route_schema.require_string(route, "definition", route_path)).resolve()
    definition = definitions[definition_path]
    return route_path, route, definition_path, definition


def scalar_offsets(scalars, route_path):
    return route_emit.scalar_offsets(scalars, route_path, route_schema)


def typed_expr(expr, scalar_type):
    return route_emit.typed_expr(expr, scalar_type)


def scalar_literal(value, scalar_type):
    return route_emit.scalar_literal(value, scalar_type)


def source_expr(source):
    return route_emit.source_expr(source)


def config_value_expr(binding):
    scalar_type = route_schema.require_string(binding, "type", "route")
    if "source" in binding:
        return typed_expr(source_expr(route_schema.require_string(binding, "source", "route")), scalar_type)
    return scalar_literal(binding["value"], scalar_type)


def config_format_args(value_var, scalar_type):
    if scalar_type in {"i32", "i64"}:
        return '"%lld"', f"static_cast<long long>({value_var})"
    if scalar_type == "f32":
        return '"%.9g"', f"static_cast<double>({value_var})"
    if scalar_type == "f64":
        return '"%.17g"', value_var
    raise ValueError(f"unsupported config type {scalar_type}")


def config_value_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_value"


def config_text_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_text"


def config_length_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_length"


def emit_config_materialization(lines, route):
    config = route_schema.require_dict(route, "config", "route")
    bindings = route_schema.require_array(config, "bindings", "route")
    for binding in bindings:
        scalar_type = route_schema.require_string(binding, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        value_var = config_value_var(binding)
        text_var = config_text_var(binding)
        length_var = config_length_var(binding)
        format_text, format_value = config_format_args(value_var, scalar_type)
        lines.extend([
            f"    const {cpp_type} {value_var} = {config_value_expr(binding)};",
            f"    char {text_var}[128] = {{}};",
            f"    const int {length_var} = std::snprintf({text_var}, sizeof({text_var}), {format_text}, {format_value});",
            f"    if ({length_var} < 0 || static_cast<size_t>({length_var}) >= sizeof({text_var})) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_CONFIG);",
            "    }",
        ])


def emit_config_plan_copy(lines, route):
    config = route_schema.require_dict(route, "config", "route")
    bindings = route_schema.require_array(config, "bindings", "route")
    for i, binding in enumerate(bindings):
        name = route_schema.require_string(binding, "name", "route")
        scalar_type = route_schema.require_string(binding, "type", "route")
        text_var = config_text_var(binding)
        lines.extend([
            f"    std::memcpy(plan->config_bindings[{i}].name, {cpp_string(name)}, sizeof({cpp_string(name)}));",
            f"    std::memcpy(plan->config_bindings[{i}].value, {text_var}, static_cast<size_t>({config_length_var(binding)}) + 1);",
            f"    plan->config_bindings[{i}].type = {cpp_string(scalar_type)};",
        ])
    lines.append(f"    plan->config_binding_count = {len(bindings)};")


def emit_integer_operand(value, context):
    return route_emit.emit_integer_operand(value, context, route_schema)


def emit_plan_materialization(lines, route, definition, context, consumed_node_indices=None):
    route_id = route_schema.require_string(route, "id", "route")
    route_constant = route_id_constant(route_id)
    invocation = route_schema.require_dict(route, "invocation", "route")
    buffers = sorted(route_schema.require_array(invocation, "buffers", "route"), key=lambda item: item["position"])
    scalars = sorted(route_schema.require_array(invocation, "scalars", "route"), key=lambda item: item["position"])
    dispatch = route_schema.require_dict(invocation, "dispatch", "route")
    abi = route_schema.require_dict(definition, "abi", "definition")
    constant_byte_length = route_schema.require_int(abi, "constant_byte_length", "definition")
    offsets, constants_size = scalar_offsets(scalars, "route")
    if constants_size != constant_byte_length:
        raise ValueError(f"route scalar size {constants_size} does not match definition constant bytes {constant_byte_length}")

    lines.append(PLAN_SETUP_TEMPLATE.format(route_id_constant=route_constant))
    emit_config_plan_copy(lines, route)

    for buffer in buffers:
        position = route_schema.require_int(buffer, "position", "route")
        tensor = route_schema.require_string(buffer, "tensor", "route")
        lines.append(BIND_BUFFER_TEMPLATE.format(
            tensor=route_emit.role_var(tensor),
            position=position,
            route_id_constant=route_constant,
        ))
    lines.append(f"    plan->binding_count = {len(buffers)};")

    for scalar, offset in zip(scalars, offsets):
        name = route_schema.require_string(scalar, "name", "route")
        scalar_type = route_schema.require_string(scalar, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        if "source" in scalar:
            value = typed_expr(source_expr(route_schema.require_string(scalar, "source", "route")), scalar_type)
        else:
            value = scalar_literal(scalar["value"], scalar_type)
        temp = f"constant_{c_identifier(name)}"
        lines.append(PACK_SCALAR_TEMPLATE.format(
            cpp_type=cpp_type,
            name=temp,
            value=value,
            offset=offset,
        ))
    lines.append(f"    plan->constants_size = {constant_byte_length};")

    lines.extend(route_emit.emit_dispatch_config(dispatch, context, route_constant, failed_response, route_schema))

    if consumed_node_indices is not None:
        if len(consumed_node_indices) > 8:
            raise ValueError(f"route consumes too many graph nodes: {len(consumed_node_indices)}")
        lines.append(f"    plan->consumed_node_count = {len(consumed_node_indices)};")
        for i, node_index in enumerate(consumed_node_indices):
            lines.append(f"    plan->consumed_node_indices[{i}] = {node_index};")

    lines.append(f"    return ggml_backend_hrx_loom_supported({route_constant});")


def fusion_op_var(op_name):
    return f"{c_identifier(op_name)}_op"


def fusion_role_expr(op_var, role):
    if role == "dst":
        return op_var
    if role.startswith("src") and role[3:].isdigit():
        return f"{op_var}->src[{int(role[3:])}]"
    raise ValueError(f"unsupported tensor role {role}")


def emit_fusion_op_setup(lines, route, route_constant):
    match = route_schema.require_dict(route, "match", "route")
    ops = route_schema.require_dict(match, "ops", "route")
    op_names = list(ops)
    matched_node_count = len(op_names)
    lines.extend([
        f"    static constexpr int matched_node_count = {matched_node_count};",
        "    if (!request->cgraph || request->node_index < 0 ||",
        "            request->node_index + matched_node_count > request->cgraph->n_nodes ||",
        "            request->cgraph->nodes[request->node_index] != node) {",
        "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "    }",
    ])
    for i, op_name in enumerate(op_names):
        op_match = route_schema.require_dict(ops[op_name], "tensors", "route")
        del op_match
        op = route_schema.require_string(ops[op_name], "op", "route")
        op_var = fusion_op_var(op_name)
        source = "node" if i == 0 else f"request->cgraph->nodes[request->node_index + {i}]"
        lines.extend([
            f"    const ggml_tensor * {op_var} = {source};",
            f"    if (!{op_var} || {op_var}->op != {op}) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "    }",
        ])

    assigned = {}
    for op_name, op_match in ops.items():
        op_var = fusion_op_var(op_name)
        op_tensors = route_schema.require_dict(op_match, "tensors", "route")
        for role, tensor_name in op_tensors.items():
            expr = fusion_role_expr(op_var, role)
            tensor_var = route_emit.role_var(tensor_name)
            if tensor_name not in assigned:
                assigned[tensor_name] = expr
                lines.append(f"    const ggml_tensor * {tensor_var} = {expr};")
            else:
                lines.extend([
                    f"    if ({tensor_var} != {expr}) {{",
                    "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE);",
                    "    }",
                ])

    tensors = route_schema.route_tensors(route, "route")
    required = sorted(name for name, tensor in tensors.items() if not tensor.get("optional", False))
    if required:
        condition = " || ".join([f"!{route_emit.role_var(name)}" for name in required])
        lines.extend([
            f"    if ({condition}) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE);",
            "    }",
        ])


def emit_fusion_attributes(lines, route):
    match = route_schema.require_dict(route, "match", "route")
    ops = route_schema.require_dict(match, "ops", "route")
    for op_name, op_match in ops.items():
        op = route_schema.require_string(op_match, "op", "route")
        attributes = op_match.get("attributes", {})
        if not attributes:
            continue
        indices = ATTRIBUTE_INDICES[op]
        op_var = fusion_op_var(op_name)
        for name, attr in attributes.items():
            scalar_type = route_schema.require_string(attr, "type", "route")
            getter = route_emit.ATTRIBUTE_GETTERS[scalar_type]
            cast = CPP_SCALAR_TYPES[scalar_type]
            lines.append(f"    const {cast} {route_emit.fusion_attribute_var(op_name, name)} = {getter}({op_var}, {indices[name]});")


def generate_fusion_route_impl(route_path, route, definition):
    match = route_schema.require_dict(route, "match", route_path)
    ops = route_schema.require_dict(match, "ops", route_path)
    anchors = match.get("anchors", [])
    anchor_name = anchors[0] if anchors else next(iter(ops))
    anchor_op = route_schema.require_string(ops[anchor_name], "op", route_path)
    route_id = route_schema.require_string(route, "id", route_path)
    function_name = route_function_name(route_id)
    route_constant = route_id_constant(route_id)
    context = route_schema.FusionRouteContext(
        route_path,
        route_schema.route_tensors(route, route_path),
        {op_name: op_match.get("attributes", {}) for op_name, op_match in ops.items()},
        route_schema.require_dict(route, "derived", route_path),
    )

    lines = []
    lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
        function_name=function_name,
        op=anchor_op,
        route_id_constant=route_constant,
    ))
    emit_fusion_op_setup(lines, route, route_constant)
    route_emit.emit_dtype_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_DTYPE",
    )
    emit_fusion_attributes(lines, route)
    route_emit.emit_shape_captures(lines, route, route_schema)
    route_emit.emit_tensor_declaration_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    )
    route_emit.emit_derived(lines, route, context, route_schema, "ggml_backend_hrx_loom_next_power_of_2")
    route_emit.emit_predicates(lines, route, context, route_schema, UNSUPPORTED_REASON_BY_PREDICATE, route_response)
    emit_config_materialization(lines, route)
    emit_plan_materialization(
        lines,
        route,
        definition,
        context,
        [f"request->node_index + {i}" for i in range(len(ops))],
    )
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_route_impl(route_path, route, definition):
    route_emit.validate_attribute_indices(route, route_path, route_schema, ATTRIBUTE_INDICES)
    if route_schema.route_is_fusion_v2(route, route_path):
        return generate_fusion_route_impl(route_path, route, definition)

    match = route_schema.require_dict(route, "match", route_path)
    op = route_schema.require_string(match, "op", f"{route_path}: match")
    op_rule = route_schema.OP_RULES[op]
    route_id = route_schema.require_string(route, "id", route_path)
    function_name = route_function_name(route_id)
    route_constant = route_id_constant(route_id)
    context = route_schema.RouteContext(
        route_path,
        op_rule,
        route_schema.route_tensors(route, route_path),
        match.get("attributes", {}),
        route_schema.require_dict(route, "derived", route_path),
    )

    lines = []
    lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
        function_name=function_name,
        op=op,
        route_id_constant=route_constant,
    ))
    route_emit.emit_tensor_setup(
        lines,
        route,
        op_rule,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    )
    route_emit.emit_dtype_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_DTYPE",
    )
    route_emit.emit_attributes(lines, route, route_schema, ATTRIBUTE_INDICES)
    route_emit.emit_shape_captures(lines, route, route_schema)
    route_emit.emit_tensor_declaration_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    )
    route_emit.emit_derived(lines, route, context, route_schema, "ggml_backend_hrx_loom_next_power_of_2")
    route_emit.emit_predicates(lines, route, context, route_schema, UNSUPPORTED_REASON_BY_PREDICATE, route_response)
    emit_config_materialization(lines, route)
    emit_plan_materialization(lines, route, definition, context)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_dispatcher_impl(routes):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]
    route_infos = route_emit.route_infos_for_dispatcher(routes, route_schema)
    ops = route_emit.ops_from_route_infos(route_infos)

    for op in ops:
        lines.extend([
            f"ggml_backend_hrx_loom_op_response {op_router_function_name(op)}(",
            "        ggml_backend_hrx_loom_catalog * catalog,",
            "        const ggml_backend_hrx_loom_op_request * request,",
            "        ggml_backend_hrx_loom_execution_plan * plan);",
            "",
        ])

    lines.append(DISPATCHER_FUNCTION_OPEN_TEMPLATE)
    for op in ops:
        lines.extend([
            f"        case {op}:",
            f"            return {op_router_function_name(op)}(catalog, request, plan);",
        ])
    lines.append(DISPATCHER_FUNCTION_CLOSE_TEMPLATE)
    return "\n".join(lines)


def generate_op_router_impl(routes, selected_op):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]

    route_infos = route_emit.route_infos_for_op(routes, selected_op, route_schema)
    if not route_infos:
        raise ValueError(f"no routes found for {selected_op}")

    for _, _, route_path, route, definition in route_infos:
        route_id = route_schema.require_string(route, "id", route_path)
        lines.extend([
            f"static constexpr const char * {route_id_constant(route_id)} = {cpp_string(route_id)};",
            "",
            generate_route_impl(route_path, route, definition),
        ])

    function_name = op_router_function_name(selected_op)
    lines.extend([
        f"ggml_backend_hrx_loom_op_response {function_name}(",
        "        ggml_backend_hrx_loom_catalog * catalog,",
        "        const ggml_backend_hrx_loom_op_request * request,",
        "        ggml_backend_hrx_loom_execution_plan * plan);",
        "",
        f"ggml_backend_hrx_loom_op_response {function_name}(",
        "        ggml_backend_hrx_loom_catalog * catalog,",
        "        const ggml_backend_hrx_loom_op_request * request,",
        "        ggml_backend_hrx_loom_execution_plan * plan) {",
        "    ggml_backend_hrx_loom_op_response fallback =",
        "        ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "",
    ])

    for _, route_id, _, _, _ in route_infos:
        lines.extend([
            "    {",
            "        ggml_backend_hrx_loom_op_response response =",
            f"            {route_function_name(route_id)}(catalog, request, plan);",
            "        if (response.result != GGML_BACKEND_HRX_LOOM_UNSUPPORTED) {",
            "            return response;",
            "        }",
            "        if (fallback.unsupported_reason == GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE &&",
            "            response.unsupported_reason != GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE) {",
            "            fallback = response;",
            "        }",
            "    }",
            "",
        ])

    lines.extend([
        "    return fallback;",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", default=str(route_validator.default_source_root()))
    parser.add_argument("--route", required=True, action="append")
    parser.add_argument("--out", required=True)
    parser.add_argument("--dispatcher", action="store_true")
    parser.add_argument("--op-router", action="store_true")
    parser.add_argument("--op")
    args = parser.parse_args()

    try:
        routes = [load_route(Path(args.source_root), route_name) for route_name in args.route]
        if args.dispatcher:
            output = generate_dispatcher_impl([(route_path, route, definition) for route_path, route, _, definition in routes])
        elif args.op_router:
            if not args.op:
                raise ValueError("--op-router expects --op")
            output = generate_op_router_impl([(route_path, route, definition) for route_path, route, _, definition in routes], args.op)
        else:
            raise ValueError("expected --dispatcher or --op-router")
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as err:
        print(f"ValueError: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
