#!/usr/bin/env python3

import argparse
import json
import sys
from pathlib import Path

import hrx_route_emit as route_emit
import hrx_route_schema as route_schema
import validate_loom_routes as route_validator



ATTRIBUTE_INDICES = route_emit.ATTRIBUTE_INDICES
CPP_SCALAR_TYPES = route_emit.CPP_SCALAR_TYPES

UNSUPPORTED_REASON_BY_PREDICATE = {
    "contiguous": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "same_shape": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "rank": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "field": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "src_absent": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "src_present": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
}

ROUTE_FUNCTION_OPEN_TEMPLATE = """static ggml_backend_hrx_loom_op_response {function_name}(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {{
    if (!catalog || !request || !request->op) {{
        return ggml_backend_hrx_loom_failed(nullptr);
    }}
    const ggml_tensor * node = request->op;
    if (node->op != {op}) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }}
    const ggml_backend_hrx_loom_catalog_entry * entry = ggml_backend_hrx_loom_find_entry(catalog, {route_id_constant});
    if (!entry) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_TARGET);
    }}"""

PLAN_SETUP_TEMPLATE = """
    if (ggml_backend_hrx_loom_match_only(plan)) {{
        return ggml_backend_hrx_loom_supported({route_id_constant});
    }}
    if (!request->stream || !request->bind_tensor) {{
        return ggml_backend_hrx_loom_failed({route_id_constant});
    }}
    std::memset(plan, 0, sizeof(*plan));
    plan->entry = entry;"""

BIND_BUFFER_TEMPLATE = """    if (!ggml_backend_hrx_loom_bind_tensor(request, {tensor}, &plan->bindings[{position}])) {{
        return ggml_backend_hrx_loom_failed({route_id_constant});
    }}"""

PACK_SCALAR_TEMPLATE = """    const {cpp_type} {name} = {value};
    std::memcpy(plan->constants + {offset}, &{name}, sizeof({name}));"""

DISPATCHER_CPP_HEADER_TEMPLATE = """// Generated by generate_loom_route_impl.py.

#include "loom-catalog/ggml-hrx-loom-catalog-runtime-internal.h"

#include <cstdio>
#include <cstring>
"""

DISPATCHER_FUNCTION_OPEN_TEMPLATE = """ggml_backend_hrx_loom_op_response ggml_backend_hrx_loom_match_or_prepare_request(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {
    if (!catalog || !request || !request->op) {
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }

    switch (request->op->op) {"""

DISPATCHER_FUNCTION_CLOSE_TEMPLATE = """        default:
            break;
    }
    return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
}
"""


cpp_string = route_emit.cpp_string


def c_identifier(value):
    return route_emit.c_identifier(value)


def route_function_name(route_id):
    return f"ggml_backend_hrx_loom_route_{c_identifier(route_id)}"


def op_router_function_name(op):
    op_name = op
    if op_name.startswith("GGML_OP_"):
        op_name = op_name[len("GGML_OP_"):]
    return f"ggml_backend_hrx_loom_router_{c_identifier(op_name).lower()}"


def route_id_constant(route_id):
    return f"GGML_HRX_LOOM_ROUTE_ID_{c_identifier(route_id).upper()}"


def loom_reason(reason):
    return reason.replace("_HSACO_", "_LOOM_")


def route_response(reason):
    return f"return ggml_backend_hrx_loom_unsupported({loom_reason(reason)});"


def load_route(source_root, route_name):
    source_root = source_root.resolve()
    route_path = Path(route_name)
    if not route_path.is_absolute():
        route_path = source_root / route_path
    route_path = route_path.resolve()

    definitions = route_validator.load_definitions(source_root)
    route_validator.validate_route(route_path, definitions)
    route = route_schema.read_json(route_path)
    definition_path = (route_path.parent / route_schema.require_string(route, "definition", route_path)).resolve()
    definition = definitions[definition_path]
    return route_path, route, definition_path, definition


def scalar_offsets(scalars, route_path):
    return route_emit.scalar_offsets(scalars, route_path, route_schema)


def typed_expr(expr, scalar_type):
    return route_emit.typed_expr(expr, scalar_type)


def scalar_literal(value, scalar_type):
    return route_emit.scalar_literal(value, scalar_type)


def source_expr(source):
    return route_emit.source_expr(source)


def config_value_expr(binding):
    scalar_type = route_schema.require_string(binding, "type", "route")
    if "source" in binding:
        return typed_expr(source_expr(route_schema.require_string(binding, "source", "route")), scalar_type)
    return scalar_literal(binding["value"], scalar_type)


def config_format_args(value_var, scalar_type):
    if scalar_type in {"i32", "i64"}:
        return '"%lld"', f"static_cast<long long>({value_var})"
    if scalar_type == "f32":
        return '"%.9g"', f"static_cast<double>({value_var})"
    if scalar_type == "f64":
        return '"%.17g"', value_var
    raise ValueError(f"unsupported config type {scalar_type}")


def config_value_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_value"


def config_text_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_text"


def config_length_var(binding):
    return f"config_{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_length"


def emit_config_materialization(lines, route):
    config = route_schema.require_dict(route, "config", "route")
    bindings = route_schema.require_array(config, "bindings", "route")
    for binding in bindings:
        scalar_type = route_schema.require_string(binding, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        value_var = config_value_var(binding)
        text_var = config_text_var(binding)
        length_var = config_length_var(binding)
        format_text, format_value = config_format_args(value_var, scalar_type)
        lines.extend([
            f"    const {cpp_type} {value_var} = {config_value_expr(binding)};",
            f"    char {text_var}[128] = {{}};",
            f"    const int {length_var} = std::snprintf({text_var}, sizeof({text_var}), {format_text}, {format_value});",
            f"    if ({length_var} < 0 || static_cast<size_t>({length_var}) >= sizeof({text_var})) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_CONFIG);",
            "    }",
        ])


def emit_config_plan_copy(lines, route):
    config = route_schema.require_dict(route, "config", "route")
    bindings = route_schema.require_array(config, "bindings", "route")
    for i, binding in enumerate(bindings):
        name = route_schema.require_string(binding, "name", "route")
        scalar_type = route_schema.require_string(binding, "type", "route")
        text_var = config_text_var(binding)
        lines.extend([
            f"    std::memcpy(plan->config_bindings[{i}].name, {cpp_string(name)}, sizeof({cpp_string(name)}));",
            f"    std::memcpy(plan->config_bindings[{i}].value, {text_var}, static_cast<size_t>({config_length_var(binding)}) + 1);",
            f"    plan->config_bindings[{i}].type = {cpp_string(scalar_type)};",
        ])
    lines.append(f"    plan->config_binding_count = {len(bindings)};")


def emit_flat_1d_dispatch(dispatch, context, route_constant):
    del context
    work_items = source_expr(route_schema.require_string(dispatch, "work_items", "route"))
    return [
        f"    if (!ggml_backend_hrx_loom_make_1d_dispatch_config(entry, {work_items}, &plan->dispatch)) {{",
        f"        return ggml_backend_hrx_loom_failed({route_constant});",
        "    }",
    ]


def emit_rows_1d_dispatch(dispatch, context, route_constant):
    del context
    rows = source_expr(route_schema.require_string(dispatch, "rows", "route"))
    return [
        f"    if (!ggml_backend_hrx_loom_make_row_dispatch_config(entry, {rows}, &plan->dispatch)) {{",
        f"        return ggml_backend_hrx_loom_failed({route_constant});",
        "    }",
    ]


def emit_integer_operand(value, context):
    return route_emit.emit_integer_operand(value, context, route_schema)


def emit_exact_3d_dispatch(dispatch, context, route_constant):
    return route_emit.emit_exact_3d_dispatch(dispatch, context, route_constant, route_schema)


DISPATCH_EMITTERS = {
    "flat_1d": emit_flat_1d_dispatch,
    "rows_1d": emit_rows_1d_dispatch,
    "exact_3d": emit_exact_3d_dispatch,
}


def emit_plan_materialization(lines, route, definition, context):
    route_id = route_schema.require_string(route, "id", "route")
    route_constant = route_id_constant(route_id)
    invocation = route_schema.require_dict(route, "invocation", "route")
    buffers = sorted(route_schema.require_array(invocation, "buffers", "route"), key=lambda item: item["position"])
    scalars = sorted(route_schema.require_array(invocation, "scalars", "route"), key=lambda item: item["position"])
    dispatch = route_schema.require_dict(invocation, "dispatch", "route")
    abi = route_schema.require_dict(definition, "abi", "definition")
    constant_byte_length = route_schema.require_int(abi, "constant_byte_length", "definition")
    offsets, constants_size = scalar_offsets(scalars, "route")
    if constants_size != constant_byte_length:
        raise ValueError(f"route scalar size {constants_size} does not match definition constant bytes {constant_byte_length}")

    lines.append(PLAN_SETUP_TEMPLATE.format(route_id_constant=route_constant))
    emit_config_plan_copy(lines, route)

    for buffer in buffers:
        position = route_schema.require_int(buffer, "position", "route")
        tensor = route_schema.require_string(buffer, "tensor", "route")
        lines.append(BIND_BUFFER_TEMPLATE.format(
            tensor=route_emit.role_var(tensor),
            position=position,
            route_id_constant=route_constant,
        ))
    lines.append(f"    plan->binding_count = {len(buffers)};")

    for scalar, offset in zip(scalars, offsets):
        name = route_schema.require_string(scalar, "name", "route")
        scalar_type = route_schema.require_string(scalar, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        if "source" in scalar:
            value = typed_expr(source_expr(route_schema.require_string(scalar, "source", "route")), scalar_type)
        else:
            value = scalar_literal(scalar["value"], scalar_type)
        temp = f"constant_{c_identifier(name)}"
        lines.append(PACK_SCALAR_TEMPLATE.format(
            cpp_type=cpp_type,
            name=temp,
            value=value,
            offset=offset,
        ))
    lines.append(f"    plan->constants_size = {constant_byte_length};")

    kind = route_schema.require_string(dispatch, "kind", "route")
    emitter = DISPATCH_EMITTERS.get(kind)
    if emitter is None:
        raise ValueError(f"unsupported dispatch kind {kind}")
    lines.extend(emitter(dispatch, context, route_constant))

    lines.append(f"    return ggml_backend_hrx_loom_supported({route_constant});")


def generate_route_impl(route_path, route, definition):
    route_emit.validate_attribute_indices(route, route_path, route_schema, ATTRIBUTE_INDICES)

    match = route_schema.require_dict(route, "match", route_path)
    op = route_schema.require_string(match, "op", f"{route_path}: match")
    op_rule = route_schema.OP_RULES[op]
    route_id = route_schema.require_string(route, "id", route_path)
    function_name = route_function_name(route_id)
    route_constant = route_id_constant(route_id)
    context = route_schema.RouteContext(
        route_path,
        op_rule,
        route_schema.require_dict(match, "tensors", route_path),
        match.get("attributes", {}),
        route_schema.require_dict(route, "derived", route_path),
    )

    lines = []
    lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
        function_name=function_name,
        op=op,
        route_id_constant=route_constant,
    ))
    route_emit.emit_tensor_setup(
        lines,
        route,
        op_rule,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    )
    route_emit.emit_dtype_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_DTYPE",
    )
    route_emit.emit_attributes(lines, route, route_schema, ATTRIBUTE_INDICES)
    route_emit.emit_shape_captures(lines, route, route_schema)
    route_emit.emit_derived(lines, route, context, route_schema, "ggml_backend_hrx_loom_next_power_of_2")
    route_emit.emit_predicates(lines, route, context, route_schema, UNSUPPORTED_REASON_BY_PREDICATE, route_response)
    emit_config_materialization(lines, route)
    emit_plan_materialization(lines, route, definition, context)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_dispatcher_impl(routes):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]
    route_infos = route_emit.route_infos_for_dispatcher(routes, route_schema)
    ops = route_emit.ops_from_route_infos(route_infos)

    for op in ops:
        lines.extend([
            f"ggml_backend_hrx_loom_op_response {op_router_function_name(op)}(",
            "        ggml_backend_hrx_loom_catalog * catalog,",
            "        const ggml_backend_hrx_loom_op_request * request,",
            "        ggml_backend_hrx_loom_execution_plan * plan);",
            "",
        ])

    lines.append(DISPATCHER_FUNCTION_OPEN_TEMPLATE)
    for op in ops:
        lines.extend([
            f"        case {op}:",
            f"            return {op_router_function_name(op)}(catalog, request, plan);",
        ])
    lines.append(DISPATCHER_FUNCTION_CLOSE_TEMPLATE)
    return "\n".join(lines)


def generate_op_router_impl(routes, selected_op):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]

    route_infos = route_emit.route_infos_for_op(routes, selected_op, route_schema)
    if not route_infos:
        raise ValueError(f"no routes found for {selected_op}")

    for _, _, route_path, route, definition in route_infos:
        route_id = route_schema.require_string(route, "id", route_path)
        lines.extend([
            f"static constexpr const char * {route_id_constant(route_id)} = {cpp_string(route_id)};",
            "",
            generate_route_impl(route_path, route, definition),
        ])

    function_name = op_router_function_name(selected_op)
    lines.extend([
        f"ggml_backend_hrx_loom_op_response {function_name}(",
        "        ggml_backend_hrx_loom_catalog * catalog,",
        "        const ggml_backend_hrx_loom_op_request * request,",
        "        ggml_backend_hrx_loom_execution_plan * plan);",
        "",
        f"ggml_backend_hrx_loom_op_response {function_name}(",
        "        ggml_backend_hrx_loom_catalog * catalog,",
        "        const ggml_backend_hrx_loom_op_request * request,",
        "        ggml_backend_hrx_loom_execution_plan * plan) {",
        "    ggml_backend_hrx_loom_op_response fallback =",
        "        ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "",
    ])

    for _, route_id, _, _, _ in route_infos:
        lines.extend([
            "    {",
            "        ggml_backend_hrx_loom_op_response response =",
            f"            {route_function_name(route_id)}(catalog, request, plan);",
            "        if (response.result != GGML_BACKEND_HRX_LOOM_UNSUPPORTED) {",
            "            return response;",
            "        }",
            "        if (fallback.unsupported_reason == GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE &&",
            "            response.unsupported_reason != GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE) {",
            "            fallback = response;",
            "        }",
            "    }",
            "",
        ])

    lines.extend([
        "    return fallback;",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", default=str(route_validator.default_source_root()))
    parser.add_argument("--route", required=True, action="append")
    parser.add_argument("--out", required=True)
    parser.add_argument("--dispatcher", action="store_true")
    parser.add_argument("--op-router", action="store_true")
    parser.add_argument("--op")
    args = parser.parse_args()

    try:
        routes = [load_route(Path(args.source_root), route_name) for route_name in args.route]
        if args.dispatcher:
            output = generate_dispatcher_impl([(route_path, route, definition) for route_path, route, _, definition in routes])
        elif args.op_router:
            if not args.op:
                raise ValueError("--op-router expects --op")
            output = generate_op_router_impl([(route_path, route, definition) for route_path, route, _, definition in routes], args.op)
        else:
            raise ValueError("expected --dispatcher or --op-router")
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as err:
        print(f"ValueError: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
