#!/usr/bin/env python3

import argparse
import json
import sys
from pathlib import Path

from utils import hrx_route_emit as route_emit
import validate_hsaco_routes as route_validator


ATTRIBUTE_INDICES = route_emit.ATTRIBUTE_INDICES
CPP_SCALAR_TYPES = route_emit.CPP_SCALAR_TYPES
CPP_DTYPE_NAMES = route_emit.CPP_DTYPE_NAMES

UNSUPPORTED_REASON_BY_PREDICATE = {
    "contiguous": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_LAYOUT",
    "same_shape": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    "rank": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    "field": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    "src_absent": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    "src_present": "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
}

ROUTE_FUNCTION_OPEN_TEMPLATE = """static ggml_backend_hrx_hsaco_op_response {function_name}(
        ggml_backend_hrx_hsaco_catalog * catalog,
        const ggml_backend_hrx_hsaco_op_request * request,
        ggml_backend_hrx_hsaco_execution_plan * plan) {{
    if (!catalog || !request || !request->op) {{
        return ggml_backend_hrx_hsaco_failed(nullptr);
    }}
    const ggml_tensor * node = request->op;
    if (node->op != {op}) {{
        return ggml_backend_hrx_hsaco_unsupported(GGML_BACKEND_HRX_HSACO_UNSUPPORTED_NO_ROUTE);
    }}
    const ggml_backend_hrx_hsaco_catalog_entry * entry = ggml_backend_hrx_hsaco_find_entry(catalog, {route_id_constant});
    if (!entry) {{
        return ggml_backend_hrx_hsaco_unsupported(GGML_BACKEND_HRX_HSACO_UNSUPPORTED_TARGET);
    }}"""

PLAN_SETUP_TEMPLATE = """
    if (ggml_backend_hrx_hsaco_match_only(plan)) {{
        return ggml_backend_hrx_hsaco_supported({route_id_constant});
    }}
    if (!request->stream || !request->bind_tensor) {{
        return ggml_backend_hrx_hsaco_failed({route_id_constant});
    }}
    std::memset(plan, 0, sizeof(*plan));
    plan->entry = entry;"""

BIND_BUFFER_TEMPLATE = """    if (!ggml_backend_hrx_hsaco_bind_tensor(request, {tensor}, &plan->bindings[{position}])) {{
        return ggml_backend_hrx_hsaco_failed({route_id_constant});
    }}"""

PACK_SCALAR_TEMPLATE = """    const {cpp_type} {name} = {value};
    std::memcpy(plan->constants + {offset}, &{name}, sizeof({name}));"""

DISPATCHER_HEADER_TEMPLATE = """// Generated by generate_hsaco_route_impl.py.
"""

DISPATCHER_CPP_HEADER_TEMPLATE = """// Generated by generate_hsaco_route_impl.py.

#include "hsaco-catalog/ggml-hrx-hsaco-catalog-runtime-internal.h"
"""

DISPATCHER_FUNCTION_OPEN_TEMPLATE = """ggml_backend_hrx_hsaco_op_response ggml_backend_hrx_hsaco_match_or_prepare_request(
        ggml_backend_hrx_hsaco_catalog * catalog,
        const ggml_backend_hrx_hsaco_op_request * request,
        ggml_backend_hrx_hsaco_execution_plan * plan) {
    if (!catalog || !request || !request->op) {
        return ggml_backend_hrx_hsaco_unsupported(GGML_BACKEND_HRX_HSACO_UNSUPPORTED_NO_ROUTE);
    }

    switch (request->op->op) {"""

DISPATCHER_FUNCTION_CLOSE_TEMPLATE = """        default:
            break;
    }
    return ggml_backend_hrx_hsaco_unsupported(GGML_BACKEND_HRX_HSACO_UNSUPPORTED_NO_ROUTE);
}
"""


cpp_string = route_emit.cpp_string
c_identifier = route_emit.c_identifier


def route_function_name(route_id):
    return f"ggml_backend_hrx_hsaco_route_{c_identifier(route_id)}"


def op_router_function_name(op):
    op_name = op
    if op_name.startswith("GGML_OP_"):
        op_name = op_name[len("GGML_OP_"):]
    return f"ggml_backend_hrx_hsaco_router_{c_identifier(op_name).lower()}"


role_expr = route_emit.role_expr
role_var = route_emit.role_var
derived_var = route_emit.derived_var
attribute_var = route_emit.attribute_var
shape_var = route_emit.shape_var


def route_id_constant(route_id):
    return f"GGML_HRX_HSACO_ROUTE_ID_{c_identifier(route_id).upper()}"


scalar_literal = route_emit.scalar_literal
source_expr = route_emit.source_expr
source_type = route_emit.source_type
typed_expr = route_emit.typed_expr


def route_response(reason):
    return f"return ggml_backend_hrx_hsaco_unsupported({reason});"


def load_route(source_root, route_name):
    source_root = source_root.resolve()
    route_path = Path(route_name)
    if not route_path.is_absolute():
        route_path = source_root / route_path
    route_path = route_path.resolve()

    definitions = route_validator.load_definitions(source_root)
    route_validator.validate_route(route_path, definitions)
    route = route_validator.read_json(route_path)
    definition_path = (route_path.parent / route_validator.require_string(route, "definition", route_path)).resolve()
    definition = definitions[definition_path]
    return route_path, route, definition_path, definition


def validate_attribute_indices(route, route_path):
    route_emit.validate_attribute_indices(route, route_path, route_validator, ATTRIBUTE_INDICES)


def scalar_offsets(scalars, route_path):
    return route_emit.scalar_offsets(scalars, route_path, route_validator)


def emit_tensor_setup(lines, route, op_rule):
    route_emit.emit_tensor_setup(
        lines,
        route,
        op_rule,
        route_validator,
        route_response,
        "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_SHAPE",
    )


def emit_dtype_checks(lines, route):
    route_emit.emit_dtype_checks(
        lines,
        route,
        route_validator,
        route_response,
        "GGML_BACKEND_HRX_HSACO_UNSUPPORTED_DTYPE",
    )


def emit_attributes(lines, route):
    route_emit.emit_attributes(lines, route, route_validator, ATTRIBUTE_INDICES)


def emit_shape_captures(lines, route):
    route_emit.emit_shape_captures(lines, route, route_validator)


def emit_integer_operand(value, context):
    return route_emit.emit_integer_operand(value, context, route_validator)


def emit_derived(lines, route, context):
    route_emit.emit_derived(lines, route, context, route_validator, "ggml_backend_hrx_hsaco_next_power_of_2")


def emit_predicates(lines, route, context):
    route_emit.emit_predicates(lines, route, context, route_validator, UNSUPPORTED_REASON_BY_PREDICATE, route_response)


def emit_flat_1d_dispatch(dispatch, context, route_constant):
    del context
    work_items = source_expr(route_validator.require_string(dispatch, "work_items", "route"))
    return [
        f"    if (!ggml_backend_hrx_hsaco_make_1d_dispatch_config(entry, {work_items}, &plan->dispatch)) {{",
        f"        return ggml_backend_hrx_hsaco_failed({route_constant});",
        "    }",
    ]


def emit_rows_1d_dispatch(dispatch, context, route_constant):
    del context
    rows = source_expr(route_validator.require_string(dispatch, "rows", "route"))
    return [
        f"    if (!ggml_backend_hrx_hsaco_make_row_dispatch_config(entry, {rows}, &plan->dispatch)) {{",
        f"        return ggml_backend_hrx_hsaco_failed({route_constant});",
        "    }",
    ]


def emit_exact_3d_dispatch(dispatch, context, route_constant):
    return route_emit.emit_exact_3d_dispatch(dispatch, context, route_constant, route_validator)


DISPATCH_EMITTERS = {
    "flat_1d": emit_flat_1d_dispatch,
    "rows_1d": emit_rows_1d_dispatch,
    "exact_3d": emit_exact_3d_dispatch,
}


def emit_plan_materialization(lines, route, definition, context):
    route_id = route_validator.require_string(route, "id", "route")
    route_constant = route_id_constant(route_id)
    invocation = route_validator.require_dict(route, "invocation", "route")
    buffers = sorted(route_validator.require_array(invocation, "buffers", "route"), key=lambda item: item["position"])
    scalars = sorted(route_validator.require_array(invocation, "scalars", "route"), key=lambda item: item["position"])
    dispatch = route_validator.require_dict(invocation, "dispatch", "route")
    abi = route_validator.require_dict(definition, "abi", "definition")
    constant_byte_length = route_validator.require_int(abi, "constant_byte_length", "definition")
    offsets, constants_size = scalar_offsets(scalars, "route")
    if constants_size != constant_byte_length:
        raise ValueError(f"route scalar size {constants_size} does not match definition constant bytes {constant_byte_length}")

    lines.append(PLAN_SETUP_TEMPLATE.format(route_id_constant=route_constant))

    for buffer in buffers:
        position = route_validator.require_int(buffer, "position", "route")
        tensor = route_validator.require_string(buffer, "tensor", "route")
        lines.append(BIND_BUFFER_TEMPLATE.format(
            tensor=role_var(tensor),
            position=position,
            route_id_constant=route_constant,
        ))
    lines.append(f"    plan->binding_count = {len(buffers)};")

    for scalar, offset in zip(scalars, offsets):
        name = route_validator.require_string(scalar, "name", "route")
        scalar_type = route_validator.require_string(scalar, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        if "source" in scalar:
            value = typed_expr(source_expr(route_validator.require_string(scalar, "source", "route")), scalar_type)
        else:
            value = scalar_literal(scalar["value"], scalar_type)
        temp = f"constant_{c_identifier(name)}"
        lines.append(PACK_SCALAR_TEMPLATE.format(
            cpp_type=cpp_type,
            name=temp,
            value=value,
            offset=offset,
        ))
    lines.append(f"    plan->constants_size = {constant_byte_length};")

    kind = route_validator.require_string(dispatch, "kind", "route")
    emitter = DISPATCH_EMITTERS.get(kind)
    if emitter is None:
        raise ValueError(f"unsupported dispatch kind {kind}")
    lines.extend(emitter(dispatch, context, route_constant))

    lines.extend([
        f"    return ggml_backend_hrx_hsaco_supported({route_constant});",
    ])


def generate_route_impl(route_path, route, definition):
    validate_attribute_indices(route, route_path)

    match = route_validator.require_dict(route, "match", route_path)
    op = route_validator.require_string(match, "op", f"{route_path}: match")
    op_rule = route_validator.OP_RULES[op]
    route_id = route_validator.require_string(route, "id", route_path)
    function_name = route_function_name(route_id)
    route_constant = route_id_constant(route_id)
    context = route_validator.RouteContext(
        route_path,
        op_rule,
        route_validator.require_dict(match, "tensors", route_path),
        match.get("attributes", {}),
        route_validator.require_dict(route, "derived", route_path),
    )

    lines = []
    lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
        function_name=function_name,
        op=op,
        route_id_constant=route_constant,
    ))
    emit_tensor_setup(lines, route, op_rule)
    emit_dtype_checks(lines, route)
    emit_attributes(lines, route)
    emit_shape_captures(lines, route)
    emit_derived(lines, route, context)
    emit_predicates(lines, route, context)
    emit_plan_materialization(lines, route, definition, context)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_dispatcher_impl(routes):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]
    route_infos = route_emit.route_infos_for_dispatcher(routes, route_validator)
    ops = route_emit.ops_from_route_infos(route_infos)

    for op in ops:
        lines.extend([
            f"ggml_backend_hrx_hsaco_op_response {op_router_function_name(op)}(",
            "        ggml_backend_hrx_hsaco_catalog * catalog,",
            "        const ggml_backend_hrx_hsaco_op_request * request,",
            "        ggml_backend_hrx_hsaco_execution_plan * plan);",
            "",
        ])

    lines.append(DISPATCHER_FUNCTION_OPEN_TEMPLATE)
    for op in ops:
        lines.extend([
            f"        case {op}:",
            f"            return {op_router_function_name(op)}(catalog, request, plan);",
        ])
    lines.append(DISPATCHER_FUNCTION_CLOSE_TEMPLATE)
    return "\n".join(lines)


def generate_op_router_impl(routes, selected_op):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]

    route_infos = route_emit.route_infos_for_op(routes, selected_op, route_validator)
    if not route_infos:
        raise ValueError(f"no routes found for {selected_op}")

    for _, _, route_path, route, definition in route_infos:
        route_id = route_validator.require_string(route, "id", route_path)
        lines.extend([
            f"static constexpr const char * {route_id_constant(route_id)} = {cpp_string(route_id)};",
            "",
            generate_route_impl(route_path, route, definition),
        ])

    function_name = op_router_function_name(selected_op)
    lines.extend([
        f"ggml_backend_hrx_hsaco_op_response {function_name}(",
        "        ggml_backend_hrx_hsaco_catalog * catalog,",
        "        const ggml_backend_hrx_hsaco_op_request * request,",
        "        ggml_backend_hrx_hsaco_execution_plan * plan);",
        "",
        f"ggml_backend_hrx_hsaco_op_response {function_name}(",
        "        ggml_backend_hrx_hsaco_catalog * catalog,",
        "        const ggml_backend_hrx_hsaco_op_request * request,",
        "        ggml_backend_hrx_hsaco_execution_plan * plan) {",
        "    ggml_backend_hrx_hsaco_op_response fallback =",
        "        ggml_backend_hrx_hsaco_unsupported(GGML_BACKEND_HRX_HSACO_UNSUPPORTED_NO_ROUTE);",
        "",
    ])

    for _, route_id, _, _, _ in route_infos:
        lines.extend([
            "    {",
            "        ggml_backend_hrx_hsaco_op_response response =",
            f"            {route_function_name(route_id)}(catalog, request, plan);",
            "        if (response.result != GGML_BACKEND_HRX_HSACO_UNSUPPORTED) {",
            "            return response;",
            "        }",
            "        if (fallback.unsupported_reason == GGML_BACKEND_HRX_HSACO_UNSUPPORTED_NO_ROUTE &&",
            "            response.unsupported_reason != GGML_BACKEND_HRX_HSACO_UNSUPPORTED_NO_ROUTE) {",
            "            fallback = response;",
            "        }",
            "    }",
            "",
        ])

    lines.extend([
        "    return fallback;",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", default=str(route_validator.default_source_root()))
    parser.add_argument("--route", required=True, action="append")
    parser.add_argument("--out", required=True)
    parser.add_argument("--dispatcher", action="store_true")
    parser.add_argument("--op-router", action="store_true")
    parser.add_argument("--op")
    args = parser.parse_args()

    try:
        routes = [load_route(Path(args.source_root), route_name) for route_name in args.route]
        if args.dispatcher:
            output = generate_dispatcher_impl([(route_path, route, definition) for route_path, route, _, definition in routes])
        elif args.op_router:
            if not args.op:
                raise ValueError("--op-router expects --op")
            output = generate_op_router_impl([(route_path, route, definition) for route_path, route, _, definition in routes], args.op)
        else:
            raise ValueError("expected --dispatcher or --op-router")
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as err:
        print(f"ValueError: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
